package com.Argeloji.Service;
// default package
// Generated Feb 27, 2013 5:08:48 PM by Hibernate Tools 3.4.0.CR1

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {

	
	private int kod;
	private String name;

	public User() {
		
		System.out.println("git deneme");
	}

	
	
	public User(int kod) {
		this.kod = kod;
	}

	public User(int kod, String name) {
		this.kod = kod;
		this.name = name;
	}

	public int getKod() {
		return this.kod;
	}

	public void setKod(int kod) {
		this.kod = kod;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
