package com.Argeloji.Domain;

// default package
// Generated Mar 18, 2013 10:44:04 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Adres generated by hbm2java
 */
public class Adres implements java.io.Serializable {

	private long kod;
	private String sokak;
	private int aptno;
	private int kapino;
	private String ilce;
	private String il;
	private int postakodu;
	private String ulke;
	private Set okuls = new HashSet(0);
	private Set kullanicis = new HashSet(0);

	public Adres() {
	}

	public Adres(long kod, String sokak, int aptno, int kapino, String ilce,
			String il, int postakodu, String ulke) {
		this.kod = kod;
		this.sokak = sokak;
		this.aptno = aptno;
		this.kapino = kapino;
		this.ilce = ilce;
		this.il = il;
		this.postakodu = postakodu;
		this.ulke = ulke;
	}

	public Adres(long kod, String sokak, int aptno, int kapino, String ilce,
			String il, int postakodu, String ulke, Set okuls, Set kullanicis) {
		this.kod = kod;
		this.sokak = sokak;
		this.aptno = aptno;
		this.kapino = kapino;
		this.ilce = ilce;
		this.il = il;
		this.postakodu = postakodu;
		this.ulke = ulke;
		this.okuls = okuls;
		this.kullanicis = kullanicis;
	}

	public long getKod() {
		return this.kod;
	}

	public void setKod(long kod) {
		this.kod = kod;
	}

	public String getSokak() {
		return this.sokak;
	}

	public void setSokak(String sokak) {
		this.sokak = sokak;
	}

	public int getAptno() {
		return this.aptno;
	}

	public void setAptno(int aptno) {
		this.aptno = aptno;
	}

	public int getKapino() {
		return this.kapino;
	}

	public void setKapino(int kapino) {
		this.kapino = kapino;
	}

	public String getIlce() {
		return this.ilce;
	}

	public void setIlce(String ilce) {
		this.ilce = ilce;
	}

	public String getIl() {
		return this.il;
	}

	public void setIl(String il) {
		this.il = il;
	}

	public int getPostakodu() {
		return this.postakodu;
	}

	public void setPostakodu(int postakodu) {
		this.postakodu = postakodu;
	}

	public String getUlke() {
		return this.ulke;
	}

	public void setUlke(String ulke) {
		this.ulke = ulke;
	}

	public Set getOkuls() {
		return this.okuls;
	}

	public void setOkuls(Set okuls) {
		this.okuls = okuls;
	}

	public Set getKullanicis() {
		return this.kullanicis;
	}

	public void setKullanicis(Set kullanicis) {
		this.kullanicis = kullanicis;
	}

}
