package com.Argeloji.Domain;

// default package
// Generated Mar 18, 2013 10:44:04 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * AltOgrenmeAlani generated by hbm2java
 */
public class AltOgrenmeAlani implements java.io.Serializable {

	private AltOgrenmeAlaniId id;
	private OgrenmeAlani ogrenmeAlani;
	private String ad;
	private Set dersSinifAltOgrenmeAlanis = new HashSet(0);

	public AltOgrenmeAlani() {
	}

	public AltOgrenmeAlani(AltOgrenmeAlaniId id, OgrenmeAlani ogrenmeAlani,
			String ad) {
		this.id = id;
		this.ogrenmeAlani = ogrenmeAlani;
		this.ad = ad;
	}

	public AltOgrenmeAlani(AltOgrenmeAlaniId id, OgrenmeAlani ogrenmeAlani,
			String ad, Set dersSinifAltOgrenmeAlanis) {
		this.id = id;
		this.ogrenmeAlani = ogrenmeAlani;
		this.ad = ad;
		this.dersSinifAltOgrenmeAlanis = dersSinifAltOgrenmeAlanis;
	}

	public AltOgrenmeAlaniId getId() {
		return this.id;
	}

	public void setId(AltOgrenmeAlaniId id) {
		this.id = id;
	}

	public OgrenmeAlani getOgrenmeAlani() {
		return this.ogrenmeAlani;
	}

	public void setOgrenmeAlani(OgrenmeAlani ogrenmeAlani) {
		this.ogrenmeAlani = ogrenmeAlani;
	}

	public String getAd() {
		return this.ad;
	}

	public void setAd(String ad) {
		this.ad = ad;
	}

	public Set getDersSinifAltOgrenmeAlanis() {
		return this.dersSinifAltOgrenmeAlanis;
	}

	public void setDersSinifAltOgrenmeAlanis(Set dersSinifAltOgrenmeAlanis) {
		this.dersSinifAltOgrenmeAlanis = dersSinifAltOgrenmeAlanis;
	}

}
