package com.Argeloji.Domain;

// default package
// Generated Mar 18, 2013 10:44:04 AM by Hibernate Tools 3.4.0.CR1

/**
 * AltOgrenmeAlaniId generated by hbm2java
 */
public class AltOgrenmeAlaniId implements java.io.Serializable {

	private int ogrenmeAlaniKod;
	private int kod;

	public AltOgrenmeAlaniId() {
	}

	public AltOgrenmeAlaniId(int ogrenmeAlaniKod, int kod) {
		this.ogrenmeAlaniKod = ogrenmeAlaniKod;
		this.kod = kod;
	}

	public int getOgrenmeAlaniKod() {
		return this.ogrenmeAlaniKod;
	}

	public void setOgrenmeAlaniKod(int ogrenmeAlaniKod) {
		this.ogrenmeAlaniKod = ogrenmeAlaniKod;
	}

	public int getKod() {
		return this.kod;
	}

	public void setKod(int kod) {
		this.kod = kod;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AltOgrenmeAlaniId))
			return false;
		AltOgrenmeAlaniId castOther = (AltOgrenmeAlaniId) other;

		return (this.getOgrenmeAlaniKod() == castOther.getOgrenmeAlaniKod())
				&& (this.getKod() == castOther.getKod());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getOgrenmeAlaniKod();
		result = 37 * result + this.getKod();
		return result;
	}

}
