package com.Argeloji.Domain;

// default package
// Generated Mar 18, 2013 10:44:04 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Altyapi generated by hbm2java
 */
public class Altyapi implements java.io.Serializable {

	private int kod;
	private Date giristarihi;
	private Set labratuars = new HashSet(0);
	private Set ifadeyeteneksinifis = new HashSet(0);
	private Set faaliyetsinifis = new HashSet(0);
	private Set okulaltyapis = new HashSet(0);
	private Set yardimciodas = new HashSet(0);

	public Altyapi() {
	}

	public Altyapi(int kod, Date giristarihi) {
		this.kod = kod;
		this.giristarihi = giristarihi;
	}

	public Altyapi(int kod, Date giristarihi, Set labratuars,
			Set ifadeyeteneksinifis, Set faaliyetsinifis, Set okulaltyapis,
			Set yardimciodas) {
		this.kod = kod;
		this.giristarihi = giristarihi;
		this.labratuars = labratuars;
		this.ifadeyeteneksinifis = ifadeyeteneksinifis;
		this.faaliyetsinifis = faaliyetsinifis;
		this.okulaltyapis = okulaltyapis;
		this.yardimciodas = yardimciodas;
	}

	public int getKod() {
		return this.kod;
	}

	public void setKod(int kod) {
		this.kod = kod;
	}

	public Date getGiristarihi() {
		return this.giristarihi;
	}

	public void setGiristarihi(Date giristarihi) {
		this.giristarihi = giristarihi;
	}

	public Set getLabratuars() {
		return this.labratuars;
	}

	public void setLabratuars(Set labratuars) {
		this.labratuars = labratuars;
	}

	public Set getIfadeyeteneksinifis() {
		return this.ifadeyeteneksinifis;
	}

	public void setIfadeyeteneksinifis(Set ifadeyeteneksinifis) {
		this.ifadeyeteneksinifis = ifadeyeteneksinifis;
	}

	public Set getFaaliyetsinifis() {
		return this.faaliyetsinifis;
	}

	public void setFaaliyetsinifis(Set faaliyetsinifis) {
		this.faaliyetsinifis = faaliyetsinifis;
	}

	public Set getOkulaltyapis() {
		return this.okulaltyapis;
	}

	public void setOkulaltyapis(Set okulaltyapis) {
		this.okulaltyapis = okulaltyapis;
	}

	public Set getYardimciodas() {
		return this.yardimciodas;
	}

	public void setYardimciodas(Set yardimciodas) {
		this.yardimciodas = yardimciodas;
	}

}
