package com.Argeloji.Domain;

// default package
// Generated Mar 18, 2013 10:44:04 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Cevapdurum generated by hbm2java
 */
public class Cevapdurum implements java.io.Serializable {

	private short kod;
	private String aciklama;
	private Set oturumSetSoruOlcmeKlasiks = new HashSet(0);
	private Set oturumSetSoruOlcmeDogruyanlises = new HashSet(0);
	private Set oturumSetSoruOlcmeCoktansecmeliTekcevaps = new HashSet(0);

	public Cevapdurum() {
	}

	public Cevapdurum(short kod, String aciklama) {
		this.kod = kod;
		this.aciklama = aciklama;
	}

	public Cevapdurum(short kod, String aciklama,
			Set oturumSetSoruOlcmeKlasiks, Set oturumSetSoruOlcmeDogruyanlises,
			Set oturumSetSoruOlcmeCoktansecmeliTekcevaps) {
		this.kod = kod;
		this.aciklama = aciklama;
		this.oturumSetSoruOlcmeKlasiks = oturumSetSoruOlcmeKlasiks;
		this.oturumSetSoruOlcmeDogruyanlises = oturumSetSoruOlcmeDogruyanlises;
		this.oturumSetSoruOlcmeCoktansecmeliTekcevaps = oturumSetSoruOlcmeCoktansecmeliTekcevaps;
	}

	public short getKod() {
		return this.kod;
	}

	public void setKod(short kod) {
		this.kod = kod;
	}

	public String getAciklama() {
		return this.aciklama;
	}

	public void setAciklama(String aciklama) {
		this.aciklama = aciklama;
	}

	public Set getOturumSetSoruOlcmeKlasiks() {
		return this.oturumSetSoruOlcmeKlasiks;
	}

	public void setOturumSetSoruOlcmeKlasiks(Set oturumSetSoruOlcmeKlasiks) {
		this.oturumSetSoruOlcmeKlasiks = oturumSetSoruOlcmeKlasiks;
	}

	public Set getOturumSetSoruOlcmeDogruyanlises() {
		return this.oturumSetSoruOlcmeDogruyanlises;
	}

	public void setOturumSetSoruOlcmeDogruyanlises(
			Set oturumSetSoruOlcmeDogruyanlises) {
		this.oturumSetSoruOlcmeDogruyanlises = oturumSetSoruOlcmeDogruyanlises;
	}

	public Set getOturumSetSoruOlcmeCoktansecmeliTekcevaps() {
		return this.oturumSetSoruOlcmeCoktansecmeliTekcevaps;
	}

	public void setOturumSetSoruOlcmeCoktansecmeliTekcevaps(
			Set oturumSetSoruOlcmeCoktansecmeliTekcevaps) {
		this.oturumSetSoruOlcmeCoktansecmeliTekcevaps = oturumSetSoruOlcmeCoktansecmeliTekcevaps;
	}

}
