package com.Argeloji.Domain;

// default package
// Generated Mar 18, 2013 10:44:04 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * CihazUygulamaOturum generated by hbm2java
 */
public class CihazUygulamaOturum implements java.io.Serializable {

	private CihazUygulamaOturumId id;
	private long kullaniciKod;
	private Date giris;
	private Date cikis;
	private int sure;

	public CihazUygulamaOturum() {
	}

	public CihazUygulamaOturum(CihazUygulamaOturumId id, long kullaniciKod,
			Date giris, Date cikis, int sure) {
		this.id = id;
		this.kullaniciKod = kullaniciKod;
		this.giris = giris;
		this.cikis = cikis;
		this.sure = sure;
	}

	public CihazUygulamaOturumId getId() {
		return this.id;
	}

	public void setId(CihazUygulamaOturumId id) {
		this.id = id;
	}

	public long getKullaniciKod() {
		return this.kullaniciKod;
	}

	public void setKullaniciKod(long kullaniciKod) {
		this.kullaniciKod = kullaniciKod;
	}

	public Date getGiris() {
		return this.giris;
	}

	public void setGiris(Date giris) {
		this.giris = giris;
	}

	public Date getCikis() {
		return this.cikis;
	}

	public void setCikis(Date cikis) {
		this.cikis = cikis;
	}

	public int getSure() {
		return this.sure;
	}

	public void setSure(int sure) {
		this.sure = sure;
	}

}
