package com.Argeloji.Domain;

// default package
// Generated Mar 18, 2013 10:44:04 AM by Hibernate Tools 3.4.0.CR1

/**
 * CihazEtkinlikOturumId generated by hbm2java
 */
public class CihazEtkinlikOturumId implements java.io.Serializable {

	private long cihazKod;
	private long etkinlikKod;
	private long oturumKod;

	public CihazEtkinlikOturumId() {
	}

	public CihazEtkinlikOturumId(long cihazKod, long etkinlikKod, long oturumKod) {
		this.cihazKod = cihazKod;
		this.etkinlikKod = etkinlikKod;
		this.oturumKod = oturumKod;
	}

	public long getCihazKod() {
		return this.cihazKod;
	}

	public void setCihazKod(long cihazKod) {
		this.cihazKod = cihazKod;
	}

	public long getEtkinlikKod() {
		return this.etkinlikKod;
	}

	public void setEtkinlikKod(long etkinlikKod) {
		this.etkinlikKod = etkinlikKod;
	}

	public long getOturumKod() {
		return this.oturumKod;
	}

	public void setOturumKod(long oturumKod) {
		this.oturumKod = oturumKod;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CihazEtkinlikOturumId))
			return false;
		CihazEtkinlikOturumId castOther = (CihazEtkinlikOturumId) other;

		return (this.getCihazKod() == castOther.getCihazKod())
				&& (this.getEtkinlikKod() == castOther.getEtkinlikKod())
				&& (this.getOturumKod() == castOther.getOturumKod());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getCihazKod();
		result = 37 * result + (int) this.getEtkinlikKod();
		result = 37 * result + (int) this.getOturumKod();
		return result;
	}

}
