package com.Argeloji.Domain;

// default package
// Generated Mar 18, 2013 10:44:04 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * CihazAlistirmaOturum generated by hbm2java
 */
public class CihazAlistirmaOturum implements java.io.Serializable {

	private CihazAlistirmaOturumId id;
	private Date giris;
	private Date cikis;
	private int sure;
	private short durum;

	public CihazAlistirmaOturum() {
	}

	public CihazAlistirmaOturum(CihazAlistirmaOturumId id, Date giris,
			Date cikis, int sure, short durum) {
		this.id = id;
		this.giris = giris;
		this.cikis = cikis;
		this.sure = sure;
		this.durum = durum;
	}

	public CihazAlistirmaOturumId getId() {
		return this.id;
	}

	public void setId(CihazAlistirmaOturumId id) {
		this.id = id;
	}

	public Date getGiris() {
		return this.giris;
	}

	public void setGiris(Date giris) {
		this.giris = giris;
	}

	public Date getCikis() {
		return this.cikis;
	}

	public void setCikis(Date cikis) {
		this.cikis = cikis;
	}

	public int getSure() {
		return this.sure;
	}

	public void setSure(int sure) {
		this.sure = sure;
	}

	public short getDurum() {
		return this.durum;
	}

	public void setDurum(short durum) {
		this.durum = durum;
	}

}
