package com.Argeloji.Domain;

// default package
// Generated Mar 18, 2013 10:44:04 AM by Hibernate Tools 3.4.0.CR1

/**
 * CihazUygulamaOturumId generated by hbm2java
 */
public class CihazUygulamaOturumId implements java.io.Serializable {

	private long cihazKod;
	private int uygulamaKod;
	private long oturumKod;

	public CihazUygulamaOturumId() {
	}

	public CihazUygulamaOturumId(long cihazKod, int uygulamaKod, long oturumKod) {
		this.cihazKod = cihazKod;
		this.uygulamaKod = uygulamaKod;
		this.oturumKod = oturumKod;
	}

	public long getCihazKod() {
		return this.cihazKod;
	}

	public void setCihazKod(long cihazKod) {
		this.cihazKod = cihazKod;
	}

	public int getUygulamaKod() {
		return this.uygulamaKod;
	}

	public void setUygulamaKod(int uygulamaKod) {
		this.uygulamaKod = uygulamaKod;
	}

	public long getOturumKod() {
		return this.oturumKod;
	}

	public void setOturumKod(long oturumKod) {
		this.oturumKod = oturumKod;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CihazUygulamaOturumId))
			return false;
		CihazUygulamaOturumId castOther = (CihazUygulamaOturumId) other;

		return (this.getCihazKod() == castOther.getCihazKod())
				&& (this.getUygulamaKod() == castOther.getUygulamaKod())
				&& (this.getOturumKod() == castOther.getOturumKod());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getCihazKod();
		result = 37 * result + this.getUygulamaKod();
		result = 37 * result + (int) this.getOturumKod();
		return result;
	}

}
