package com.Argeloji.Domain;

// default package
// Generated Mar 18, 2013 10:44:04 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Cihaz generated by hbm2java
 */
public class Cihaz implements java.io.Serializable {

	private long kod;
	private String androidId;
	private String macAddress;
	private Set uygulamaCihazs = new HashSet(0);
	private Set oturumSetSoruOlcmeDogruyanlises = new HashSet(0);
	private Set oturumSetSoruOlcmeKlasiks = new HashSet(0);
	private Set oturumSetSoruOlcmeCoktansecmeliTekcevaps = new HashSet(0);

	public Cihaz() {
	}

	public Cihaz(long kod, String androidId, String macAddress) {
		this.kod = kod;
		this.androidId = androidId;
		this.macAddress = macAddress;
	}

	public Cihaz(long kod, String androidId, String macAddress,
			Set uygulamaCihazs, Set oturumSetSoruOlcmeDogruyanlises,
			Set oturumSetSoruOlcmeKlasiks,
			Set oturumSetSoruOlcmeCoktansecmeliTekcevaps) {
		this.kod = kod;
		this.androidId = androidId;
		this.macAddress = macAddress;
		this.uygulamaCihazs = uygulamaCihazs;
		this.oturumSetSoruOlcmeDogruyanlises = oturumSetSoruOlcmeDogruyanlises;
		this.oturumSetSoruOlcmeKlasiks = oturumSetSoruOlcmeKlasiks;
		this.oturumSetSoruOlcmeCoktansecmeliTekcevaps = oturumSetSoruOlcmeCoktansecmeliTekcevaps;
	}

	public long getKod() {
		return this.kod;
	}

	public void setKod(long kod) {
		this.kod = kod;
	}

	public String getAndroidId() {
		return this.androidId;
	}

	public void setAndroidId(String androidId) {
		this.androidId = androidId;
	}

	public String getMacAddress() {
		return this.macAddress;
	}

	public void setMacAddress(String macAddress) {
		this.macAddress = macAddress;
	}

	public Set getUygulamaCihazs() {
		return this.uygulamaCihazs;
	}

	public void setUygulamaCihazs(Set uygulamaCihazs) {
		this.uygulamaCihazs = uygulamaCihazs;
	}

	public Set getOturumSetSoruOlcmeDogruyanlises() {
		return this.oturumSetSoruOlcmeDogruyanlises;
	}

	public void setOturumSetSoruOlcmeDogruyanlises(
			Set oturumSetSoruOlcmeDogruyanlises) {
		this.oturumSetSoruOlcmeDogruyanlises = oturumSetSoruOlcmeDogruyanlises;
	}

	public Set getOturumSetSoruOlcmeKlasiks() {
		return this.oturumSetSoruOlcmeKlasiks;
	}

	public void setOturumSetSoruOlcmeKlasiks(Set oturumSetSoruOlcmeKlasiks) {
		this.oturumSetSoruOlcmeKlasiks = oturumSetSoruOlcmeKlasiks;
	}

	public Set getOturumSetSoruOlcmeCoktansecmeliTekcevaps() {
		return this.oturumSetSoruOlcmeCoktansecmeliTekcevaps;
	}

	public void setOturumSetSoruOlcmeCoktansecmeliTekcevaps(
			Set oturumSetSoruOlcmeCoktansecmeliTekcevaps) {
		this.oturumSetSoruOlcmeCoktansecmeliTekcevaps = oturumSetSoruOlcmeCoktansecmeliTekcevaps;
	}

}
