package com.Argeloji.Domain;



// default package
// Generated Mar 18, 2013 3:40:30 PM by Hibernate Tools 3.4.0.CR1

/**
 * Coktansecmeli3TekcevapId generated by hbm2java
 */
public class Coktansecmeli3TekcevapId implements java.io.Serializable {

	private long soruKod;
	private String secenek1metin;
	private long secenek1GorselKod;
	private String secenek2metin;
	private long secenek2GorselKod;
	private String secenek3metin;
	private long secenek3GorselKod;
	private short secenekgorselkonum;
	private short dogrusecenek;

	public Coktansecmeli3TekcevapId() {
	}

	public Coktansecmeli3TekcevapId(long soruKod, String secenek1metin,
			long secenek1GorselKod, String secenek2metin,
			long secenek2GorselKod, String secenek3metin,
			long secenek3GorselKod, short secenekgorselkonum, short dogrusecenek) {
		this.soruKod = soruKod;
		this.secenek1metin = secenek1metin;
		this.secenek1GorselKod = secenek1GorselKod;
		this.secenek2metin = secenek2metin;
		this.secenek2GorselKod = secenek2GorselKod;
		this.secenek3metin = secenek3metin;
		this.secenek3GorselKod = secenek3GorselKod;
		this.secenekgorselkonum = secenekgorselkonum;
		this.dogrusecenek = dogrusecenek;
	}

	public long getSoruKod() {
		return this.soruKod;
	}

	public void setSoruKod(long soruKod) {
		this.soruKod = soruKod;
	}

	public String getSecenek1metin() {
		return this.secenek1metin;
	}

	public void setSecenek1metin(String secenek1metin) {
		this.secenek1metin = secenek1metin;
	}

	public long getSecenek1GorselKod() {
		return this.secenek1GorselKod;
	}

	public void setSecenek1GorselKod(long secenek1GorselKod) {
		this.secenek1GorselKod = secenek1GorselKod;
	}

	public String getSecenek2metin() {
		return this.secenek2metin;
	}

	public void setSecenek2metin(String secenek2metin) {
		this.secenek2metin = secenek2metin;
	}

	public long getSecenek2GorselKod() {
		return this.secenek2GorselKod;
	}

	public void setSecenek2GorselKod(long secenek2GorselKod) {
		this.secenek2GorselKod = secenek2GorselKod;
	}

	public String getSecenek3metin() {
		return this.secenek3metin;
	}

	public void setSecenek3metin(String secenek3metin) {
		this.secenek3metin = secenek3metin;
	}

	public long getSecenek3GorselKod() {
		return this.secenek3GorselKod;
	}

	public void setSecenek3GorselKod(long secenek3GorselKod) {
		this.secenek3GorselKod = secenek3GorselKod;
	}

	public short getSecenekgorselkonum() {
		return this.secenekgorselkonum;
	}

	public void setSecenekgorselkonum(short secenekgorselkonum) {
		this.secenekgorselkonum = secenekgorselkonum;
	}

	public short getDogrusecenek() {
		return this.dogrusecenek;
	}

	public void setDogrusecenek(short dogrusecenek) {
		this.dogrusecenek = dogrusecenek;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof Coktansecmeli3TekcevapId))
			return false;
		Coktansecmeli3TekcevapId castOther = (Coktansecmeli3TekcevapId) other;

		return (this.getSoruKod() == castOther.getSoruKod())
				&& ((this.getSecenek1metin() == castOther.getSecenek1metin()) || (this
						.getSecenek1metin() != null
						&& castOther.getSecenek1metin() != null && this
						.getSecenek1metin()
						.equals(castOther.getSecenek1metin())))
				&& (this.getSecenek1GorselKod() == castOther
						.getSecenek1GorselKod())
				&& ((this.getSecenek2metin() == castOther.getSecenek2metin()) || (this
						.getSecenek2metin() != null
						&& castOther.getSecenek2metin() != null && this
						.getSecenek2metin()
						.equals(castOther.getSecenek2metin())))
				&& (this.getSecenek2GorselKod() == castOther
						.getSecenek2GorselKod())
				&& ((this.getSecenek3metin() == castOther.getSecenek3metin()) || (this
						.getSecenek3metin() != null
						&& castOther.getSecenek3metin() != null && this
						.getSecenek3metin()
						.equals(castOther.getSecenek3metin())))
				&& (this.getSecenek3GorselKod() == castOther
						.getSecenek3GorselKod())
				&& (this.getSecenekgorselkonum() == castOther
						.getSecenekgorselkonum())
				&& (this.getDogrusecenek() == castOther.getDogrusecenek());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getSoruKod();
		result = 37
				* result
				+ (getSecenek1metin() == null ? 0 : this.getSecenek1metin()
						.hashCode());
		result = 37 * result + (int) this.getSecenek1GorselKod();
		result = 37
				* result
				+ (getSecenek2metin() == null ? 0 : this.getSecenek2metin()
						.hashCode());
		result = 37 * result + (int) this.getSecenek2GorselKod();
		result = 37
				* result
				+ (getSecenek3metin() == null ? 0 : this.getSecenek3metin()
						.hashCode());
		result = 37 * result + (int) this.getSecenek3GorselKod();
		result = 37 * result + this.getSecenekgorselkonum();
		result = 37 * result + this.getDogrusecenek();
		return result;
	}

}
