package com.Argeloji.Domain;


// default package
// Generated Mar 18, 2013 3:40:30 PM by Hibernate Tools 3.4.0.CR1

/**
 * Coktansecmeli3Tekcevap generated by hbm2java
 */
public class Coktansecmeli3Tekcevap implements java.io.Serializable {

	private Coktansecmeli3TekcevapId id;
	private Soru soru;
	private Gorsel gorselBySecenek1GorselKod;
	private Gorsel gorselBySecenek3GorselKod;
	private Gorsel gorselBySecenek2GorselKod;

	public Coktansecmeli3Tekcevap() {
	}

	public Coktansecmeli3Tekcevap(Coktansecmeli3TekcevapId id, Soru soru,
			Gorsel gorselBySecenek1GorselKod, Gorsel gorselBySecenek3GorselKod,
			Gorsel gorselBySecenek2GorselKod) {
		this.id = id;
		this.soru = soru;
		this.gorselBySecenek1GorselKod = gorselBySecenek1GorselKod;
		this.gorselBySecenek3GorselKod = gorselBySecenek3GorselKod;
		this.gorselBySecenek2GorselKod = gorselBySecenek2GorselKod;
	}

	public Coktansecmeli3TekcevapId getId() {
		return this.id;
	}

	public void setId(Coktansecmeli3TekcevapId id) {
		this.id = id;
	}

	public Soru getSoru() {
		return this.soru;
	}

	public void setSoru(Soru soru) {
		this.soru = soru;
	}

	public Gorsel getGorselBySecenek1GorselKod() {
		return this.gorselBySecenek1GorselKod;
	}

	public void setGorselBySecenek1GorselKod(Gorsel gorselBySecenek1GorselKod) {
		this.gorselBySecenek1GorselKod = gorselBySecenek1GorselKod;
	}

	public Gorsel getGorselBySecenek3GorselKod() {
		return this.gorselBySecenek3GorselKod;
	}

	public void setGorselBySecenek3GorselKod(Gorsel gorselBySecenek3GorselKod) {
		this.gorselBySecenek3GorselKod = gorselBySecenek3GorselKod;
	}

	public Gorsel getGorselBySecenek2GorselKod() {
		return this.gorselBySecenek2GorselKod;
	}

	public void setGorselBySecenek2GorselKod(Gorsel gorselBySecenek2GorselKod) {
		this.gorselBySecenek2GorselKod = gorselBySecenek2GorselKod;
	}

}
