package com.Argeloji.Domain;

// default package
// Generated Mar 18, 2013 10:44:04 AM by Hibernate Tools 3.4.0.CR1

/**
 * DersSinifId generated by hbm2java
 */
public class DersSinifId implements java.io.Serializable {

	private int dersKod;
	private int sinifKod;

	public DersSinifId() {
	}

	public DersSinifId(int dersKod, int sinifKod) {
		this.dersKod = dersKod;
		this.sinifKod = sinifKod;
	}

	public int getDersKod() {
		return this.dersKod;
	}

	public void setDersKod(int dersKod) {
		this.dersKod = dersKod;
	}

	public int getSinifKod() {
		return this.sinifKod;
	}

	public void setSinifKod(int sinifKod) {
		this.sinifKod = sinifKod;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DersSinifId))
			return false;
		DersSinifId castOther = (DersSinifId) other;

		return (this.getDersKod() == castOther.getDersKod())
				&& (this.getSinifKod() == castOther.getSinifKod());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getDersKod();
		result = 37 * result + this.getSinifKod();
		return result;
	}

}
