package com.Argeloji.Domain;

// default package
// Generated Mar 18, 2013 10:44:04 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * DersSinifAltOgrenmeAlani generated by hbm2java
 */
public class DersSinifAltOgrenmeAlani implements java.io.Serializable {

	private int kod;
	private AltOgrenmeAlani altOgrenmeAlani;
	private DersSinif dersSinif;
	private int sira;
	private Set kazanims = new HashSet(0);

	public DersSinifAltOgrenmeAlani() {
	}

	public DersSinifAltOgrenmeAlani(int kod, AltOgrenmeAlani altOgrenmeAlani,
			DersSinif dersSinif, int sira) {
		this.kod = kod;
		this.altOgrenmeAlani = altOgrenmeAlani;
		this.dersSinif = dersSinif;
		this.sira = sira;
	}

	public DersSinifAltOgrenmeAlani(int kod, AltOgrenmeAlani altOgrenmeAlani,
			DersSinif dersSinif, int sira, Set kazanims) {
		this.kod = kod;
		this.altOgrenmeAlani = altOgrenmeAlani;
		this.dersSinif = dersSinif;
		this.sira = sira;
		this.kazanims = kazanims;
	}

	public int getKod() {
		return this.kod;
	}

	public void setKod(int kod) {
		this.kod = kod;
	}

	public AltOgrenmeAlani getAltOgrenmeAlani() {
		return this.altOgrenmeAlani;
	}

	public void setAltOgrenmeAlani(AltOgrenmeAlani altOgrenmeAlani) {
		this.altOgrenmeAlani = altOgrenmeAlani;
	}

	public DersSinif getDersSinif() {
		return this.dersSinif;
	}

	public void setDersSinif(DersSinif dersSinif) {
		this.dersSinif = dersSinif;
	}

	public int getSira() {
		return this.sira;
	}

	public void setSira(int sira) {
		this.sira = sira;
	}

	public Set getKazanims() {
		return this.kazanims;
	}

	public void setKazanims(Set kazanims) {
		this.kazanims = kazanims;
	}

}
