package com.Argeloji.Domain;

// default package
// Generated Mar 18, 2013 10:44:04 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Ders generated by hbm2java
 */
public class Ders implements java.io.Serializable {

	private int kod;
	private String ad;
	private Set dersSinifs = new HashSet(0);

	public Ders() {
	}

	public Ders(int kod, String ad) {
		this.kod = kod;
		this.ad = ad;
	}

	public Ders(int kod, String ad, Set dersSinifs) {
		this.kod = kod;
		this.ad = ad;
		this.dersSinifs = dersSinifs;
	}

	public int getKod() {
		return this.kod;
	}

	public void setKod(int kod) {
		this.kod = kod;
	}

	public String getAd() {
		return this.ad;
	}

	public void setAd(String ad) {
		this.ad = ad;
	}

	public Set getDersSinifs() {
		return this.dersSinifs;
	}

	public void setDersSinifs(Set dersSinifs) {
		this.dersSinifs = dersSinifs;
	}

}
