package com.Argeloji.Domain;

// default package
// Generated Mar 18, 2013 10:44:04 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * DersSinif generated by hbm2java
 */
public class DersSinif implements java.io.Serializable {

	private DersSinifId id;
	private Ders ders;
	private Sinif sinif;
	private Set dersSinifAltOgrenmeAlanis = new HashSet(0);

	public DersSinif() {
	}

	public DersSinif(DersSinifId id, Ders ders, Sinif sinif) {
		this.id = id;
		this.ders = ders;
		this.sinif = sinif;
	}

	public DersSinif(DersSinifId id, Ders ders, Sinif sinif,
			Set dersSinifAltOgrenmeAlanis) {
		this.id = id;
		this.ders = ders;
		this.sinif = sinif;
		this.dersSinifAltOgrenmeAlanis = dersSinifAltOgrenmeAlanis;
	}

	public DersSinifId getId() {
		return this.id;
	}

	public void setId(DersSinifId id) {
		this.id = id;
	}

	public Ders getDers() {
		return this.ders;
	}

	public void setDers(Ders ders) {
		this.ders = ders;
	}

	public Sinif getSinif() {
		return this.sinif;
	}

	public void setSinif(Sinif sinif) {
		this.sinif = sinif;
	}

	public Set getDersSinifAltOgrenmeAlanis() {
		return this.dersSinifAltOgrenmeAlanis;
	}

	public void setDersSinifAltOgrenmeAlanis(Set dersSinifAltOgrenmeAlanis) {
		this.dersSinifAltOgrenmeAlanis = dersSinifAltOgrenmeAlanis;
	}

}
