package com.Argeloji.Domain;

// default package
// Generated Mar 18, 2013 10:44:04 AM by Hibernate Tools 3.4.0.CR1

/**
 * Dogruyanlis generated by hbm2java
 */
public class Dogruyanlis implements java.io.Serializable {

	private DogruyanlisId id;
	private Soru soru;

	public Dogruyanlis() {
	}

	public Dogruyanlis(DogruyanlisId id, Soru soru) {
		this.id = id;
		this.soru = soru;
	}

	public DogruyanlisId getId() {
		return this.id;
	}

	public void setId(DogruyanlisId id) {
		this.id = id;
	}

	public Soru getSoru() {
		return this.soru;
	}

	public void setSoru(Soru soru) {
		this.soru = soru;
	}

}
