package com.Argeloji.Domain;

// default package
// Generated Mar 19, 2013 1:29:16 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Etkinlik generated by hbm2java
 */
public class Etkinlik implements java.io.Serializable {

	private long kod;
	private Uygulama uygulama;
	private String ad;
	private String aciklama;
	private int sira;
	private Set sorus = new HashSet(0);

	public Etkinlik() {
	}

	public Etkinlik(long kod, Uygulama uygulama, String ad, String aciklama,
			int sira) {
		this.kod = kod;
		this.uygulama = uygulama;
		this.ad = ad;
		this.aciklama = aciklama;
		this.sira = sira;
	}

	public Etkinlik(long kod, Uygulama uygulama, String ad, String aciklama,
			int sira, Set sorus) {
		this.kod = kod;
		this.uygulama = uygulama;
		this.ad = ad;
		this.aciklama = aciklama;
		this.sira = sira;
		this.sorus = sorus;
	}

	public long getKod() {
		return this.kod;
	}

	public void setKod(long kod) {
		this.kod = kod;
	}

	public Uygulama getUygulama() {
		return this.uygulama;
	}

	public void setUygulama(Uygulama uygulama) {
		this.uygulama = uygulama;
	}

	public String getAd() {
		return this.ad;
	}

	public void setAd(String ad) {
		this.ad = ad;
	}

	public String getAciklama() {
		return this.aciklama;
	}

	public void setAciklama(String aciklama) {
		this.aciklama = aciklama;
	}

	public int getSira() {
		return this.sira;
	}

	public void setSira(int sira) {
		this.sira = sira;
	}

	public Set getSorus() {
		return this.sorus;
	}

	public void setSorus(Set sorus) {
		this.sorus = sorus;
	}

}
