package com.Argeloji.Domain;
// default package
// Generated 01.Nis.2013 21:40:36 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * Faaliyetsinifi generated by hbm2java
 */
public class Faaliyetsinifi implements java.io.Serializable {

	private int kod;
	private Altyapi altyapi;
	private Date giristarih;
	private Date cikistarih;
	private String tip;
	private String ad;
	private int kapasite;

	public Faaliyetsinifi() {
	}

	public Faaliyetsinifi(int kod, Altyapi altyapi, Date giristarih,
			Date cikistarih, String tip, String ad, int kapasite) {
		this.kod = kod;
		this.altyapi = altyapi;
		this.giristarih = giristarih;
		this.cikistarih = cikistarih;
		this.tip = tip;
		this.ad = ad;
		this.kapasite = kapasite;
	}

	public int getKod() {
		return this.kod;
	}

	public void setKod(int kod) {
		this.kod = kod;
	}

	public Altyapi getAltyapi() {
		return this.altyapi;
	}

	public void setAltyapi(Altyapi altyapi) {
		this.altyapi = altyapi;
	}

	public Date getGiristarih() {
		return this.giristarih;
	}

	public void setGiristarih(Date giristarih) {
		this.giristarih = giristarih;
	}

	public Date getCikistarih() {
		return this.cikistarih;
	}

	public void setCikistarih(Date cikistarih) {
		this.cikistarih = cikistarih;
	}

	public String getTip() {
		return this.tip;
	}

	public void setTip(String tip) {
		this.tip = tip;
	}

	public String getAd() {
		return this.ad;
	}

	public void setAd(String ad) {
		this.ad = ad;
	}

	public int getKapasite() {
		return this.kapasite;
	}

	public void setKapasite(int kapasite) {
		this.kapasite = kapasite;
	}

}
