package com.Argeloji.Domain;

// default package
// Generated Mar 18, 2013 10:44:04 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Faaliyetsinifi generated by hbm2java
 */
public class Faaliyetsinifi implements java.io.Serializable {

	private FaaliyetsinifiId id;
	private Altyapi altyapi;
	private Date giristarih;
	private Date cikistarih;
	private String tip;
	private String ad;
	private int kapasite;

	public Faaliyetsinifi() {
	}

	public Faaliyetsinifi(FaaliyetsinifiId id, Altyapi altyapi,
			Date giristarih, Date cikistarih, String tip, String ad,
			int kapasite) {
		this.id = id;
		this.altyapi = altyapi;
		this.giristarih = giristarih;
		this.cikistarih = cikistarih;
		this.tip = tip;
		this.ad = ad;
		this.kapasite = kapasite;
	}

	public FaaliyetsinifiId getId() {
		return this.id;
	}

	public void setId(FaaliyetsinifiId id) {
		this.id = id;
	}

	public Altyapi getAltyapi() {
		return this.altyapi;
	}

	public void setAltyapi(Altyapi altyapi) {
		this.altyapi = altyapi;
	}

	public Date getGiristarih() {
		return this.giristarih;
	}

	public void setGiristarih(Date giristarih) {
		this.giristarih = giristarih;
	}

	public Date getCikistarih() {
		return this.cikistarih;
	}

	public void setCikistarih(Date cikistarih) {
		this.cikistarih = cikistarih;
	}

	public String getTip() {
		return this.tip;
	}

	public void setTip(String tip) {
		this.tip = tip;
	}

	public String getAd() {
		return this.ad;
	}

	public void setAd(String ad) {
		this.ad = ad;
	}

	public int getKapasite() {
		return this.kapasite;
	}

	public void setKapasite(int kapasite) {
		this.kapasite = kapasite;
	}

}
