package com.Argeloji.Domain;

// default package
// Generated Mar 18, 2013 10:44:04 AM by Hibernate Tools 3.4.0.CR1

/**
 * Fonksiyonad generated by hbm2java
 */
public class Fonksiyonad implements java.io.Serializable {

	private int kod;
	private String ad;

	public Fonksiyonad() {
	}

	public Fonksiyonad(int kod, String ad) {
		this.kod = kod;
		this.ad = ad;
	}

	public int getKod() {
		return this.kod;
	}

	public void setKod(int kod) {
		this.kod = kod;
	}

	public String getAd() {
		return this.ad;
	}

	public void setAd(String ad) {
		this.ad = ad;
	}

}
