package com.Argeloji.Domain;

// default package
// Generated Mar 18, 2013 10:44:04 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Gorsel generated by hbm2java
 */
public class Gorsel implements java.io.Serializable {

	private long kod;
	private String dosyaad;
	private String dizin;
	private short kalitetip;
	private short dosyatip;
	private Set sorus = new HashSet(0);

	public Gorsel() {
	}

	public Gorsel(long kod, String dosyaad, String dizin, short kalitetip,
			short dosyatip) {
		this.kod = kod;
		this.dosyaad = dosyaad;
		this.dizin = dizin;
		this.kalitetip = kalitetip;
		this.dosyatip = dosyatip;
	}

	public Gorsel(long kod, String dosyaad, String dizin, short kalitetip,
			short dosyatip, Set sorus) {
		this.kod = kod;
		this.dosyaad = dosyaad;
		this.dizin = dizin;
		this.kalitetip = kalitetip;
		this.dosyatip = dosyatip;
		this.sorus = sorus;
	}

	public long getKod() {
		return this.kod;
	}

	public void setKod(long kod) {
		this.kod = kod;
	}

	public String getDosyaad() {
		return this.dosyaad;
	}

	public void setDosyaad(String dosyaad) {
		this.dosyaad = dosyaad;
	}

	public String getDizin() {
		return this.dizin;
	}

	public void setDizin(String dizin) {
		this.dizin = dizin;
	}

	public short getKalitetip() {
		return this.kalitetip;
	}

	public void setKalitetip(short kalitetip) {
		this.kalitetip = kalitetip;
	}

	public short getDosyatip() {
		return this.dosyatip;
	}

	public void setDosyatip(short dosyatip) {
		this.dosyatip = dosyatip;
	}

	public Set getSorus() {
		return this.sorus;
	}

	public void setSorus(Set sorus) {
		this.sorus = sorus;
	}

}
