package com.Argeloji.Domain;

// default package
// Generated Mar 18, 2013 10:44:04 AM by Hibernate Tools 3.4.0.CR1

/**
 * Idari generated by hbm2java
 */
public class Idari implements java.io.Serializable {

	private long kullaniciPersonelKod;
	private Personel personel;
	private String gorev;

	public Idari() {
	}

	public Idari(long kullaniciPersonelKod, Personel personel, String gorev) {
		this.kullaniciPersonelKod = kullaniciPersonelKod;
		this.personel = personel;
		this.gorev = gorev;
	}

	public long getKullaniciPersonelKod() {
		return this.kullaniciPersonelKod;
	}

	public void setKullaniciPersonelKod(long kullaniciPersonelKod) {
		this.kullaniciPersonelKod = kullaniciPersonelKod;
	}

	public Personel getPersonel() {
		return this.personel;
	}

	public void setPersonel(Personel personel) {
		this.personel = personel;
	}

	public String getGorev() {
		return this.gorev;
	}

	public void setGorev(String gorev) {
		this.gorev = gorev;
	}

}
