package com.Argeloji.Domain;

// default package
// Generated Mar 18, 2013 10:44:04 AM by Hibernate Tools 3.4.0.CR1

/**
 * IfadeyeteneksinifiId generated by hbm2java
 */
public class IfadeyeteneksinifiId implements java.io.Serializable {

	private int kod;
	private int altyapiKod;

	public IfadeyeteneksinifiId() {
	}

	public IfadeyeteneksinifiId(int kod, int altyapiKod) {
		this.kod = kod;
		this.altyapiKod = altyapiKod;
	}

	public int getKod() {
		return this.kod;
	}

	public void setKod(int kod) {
		this.kod = kod;
	}

	public int getAltyapiKod() {
		return this.altyapiKod;
	}

	public void setAltyapiKod(int altyapiKod) {
		this.altyapiKod = altyapiKod;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof IfadeyeteneksinifiId))
			return false;
		IfadeyeteneksinifiId castOther = (IfadeyeteneksinifiId) other;

		return (this.getKod() == castOther.getKod())
				&& (this.getAltyapiKod() == castOther.getAltyapiKod());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getKod();
		result = 37 * result + this.getAltyapiKod();
		return result;
	}

}
