package com.Argeloji.Domain;

// default package
// Generated Mar 18, 2013 10:44:04 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Ifadeyeteneksinifi generated by hbm2java
 */
public class Ifadeyeteneksinifi implements java.io.Serializable {

	private IfadeyeteneksinifiId id;
	private Altyapi altyapi;
	private String klupadi;
	private Date cikistarih;
	private Date giristarih;
	private String ad;

	public Ifadeyeteneksinifi() {
	}

	public Ifadeyeteneksinifi(IfadeyeteneksinifiId id, Altyapi altyapi,
			String klupadi, Date cikistarih, Date giristarih, String ad) {
		this.id = id;
		this.altyapi = altyapi;
		this.klupadi = klupadi;
		this.cikistarih = cikistarih;
		this.giristarih = giristarih;
		this.ad = ad;
	}

	public IfadeyeteneksinifiId getId() {
		return this.id;
	}

	public void setId(IfadeyeteneksinifiId id) {
		this.id = id;
	}

	public Altyapi getAltyapi() {
		return this.altyapi;
	}

	public void setAltyapi(Altyapi altyapi) {
		this.altyapi = altyapi;
	}

	public String getKlupadi() {
		return this.klupadi;
	}

	public void setKlupadi(String klupadi) {
		this.klupadi = klupadi;
	}

	public Date getCikistarih() {
		return this.cikistarih;
	}

	public void setCikistarih(Date cikistarih) {
		this.cikistarih = cikistarih;
	}

	public Date getGiristarih() {
		return this.giristarih;
	}

	public void setGiristarih(Date giristarih) {
		this.giristarih = giristarih;
	}

	public String getAd() {
		return this.ad;
	}

	public void setAd(String ad) {
		this.ad = ad;
	}

}
