package com.Argeloji.Domain;
// default package
// Generated 01.Nis.2013 21:40:36 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * İfadeyeteneksinifi generated by hbm2java
 */
public class İfadeyeteneksinifi implements java.io.Serializable {

	private int kod;
	private Altyapi altyapi;
	private String klupadi;
	private Date cikistarih;
	private Date giristarih;
	private String ad;

	public İfadeyeteneksinifi() {
	}

	public İfadeyeteneksinifi(int kod, Altyapi altyapi, String klupadi,
			Date cikistarih, Date giristarih, String ad) {
		this.kod = kod;
		this.altyapi = altyapi;
		this.klupadi = klupadi;
		this.cikistarih = cikistarih;
		this.giristarih = giristarih;
		this.ad = ad;
	}

	public int getKod() {
		return this.kod;
	}

	public void setKod(int kod) {
		this.kod = kod;
	}

	public Altyapi getAltyapi() {
		return this.altyapi;
	}

	public void setAltyapi(Altyapi altyapi) {
		this.altyapi = altyapi;
	}

	public String getKlupadi() {
		return this.klupadi;
	}

	public void setKlupadi(String klupadi) {
		this.klupadi = klupadi;
	}

	public Date getCikistarih() {
		return this.cikistarih;
	}

	public void setCikistarih(Date cikistarih) {
		this.cikistarih = cikistarih;
	}

	public Date getGiristarih() {
		return this.giristarih;
	}

	public void setGiristarih(Date giristarih) {
		this.giristarih = giristarih;
	}

	public String getAd() {
		return this.ad;
	}

	public void setAd(String ad) {
		this.ad = ad;
	}

}
