package com.Argeloji.Domain;

// default package
// Generated Mar 18, 2013 10:44:04 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Kademe generated by hbm2java
 */
public class Kademe implements java.io.Serializable {

	private int kod;
	private String ad;
	private Set kulups = new HashSet(0);
	private Set sinifs = new HashSet(0);
	private Set okulkademes = new HashSet(0);
	private Set okulzumres = new HashSet(0);

	public Kademe() {
	}

	public Kademe(int kod, String ad) {
		this.kod = kod;
		this.ad = ad;
	}

	public Kademe(int kod, String ad, Set kulups, Set sinifs, Set okulkademes,
			Set okulzumres) {
		this.kod = kod;
		this.ad = ad;
		this.kulups = kulups;
		this.sinifs = sinifs;
		this.okulkademes = okulkademes;
		this.okulzumres = okulzumres;
	}

	public int getKod() {
		return this.kod;
	}

	public void setKod(int kod) {
		this.kod = kod;
	}

	public String getAd() {
		return this.ad;
	}

	public void setAd(String ad) {
		this.ad = ad;
	}

	public Set getKulups() {
		return this.kulups;
	}

	public void setKulups(Set kulups) {
		this.kulups = kulups;
	}

	public Set getSinifs() {
		return this.sinifs;
	}

	public void setSinifs(Set sinifs) {
		this.sinifs = sinifs;
	}

	public Set getOkulkademes() {
		return this.okulkademes;
	}

	public void setOkulkademes(Set okulkademes) {
		this.okulkademes = okulkademes;
	}

	public Set getOkulzumres() {
		return this.okulzumres;
	}

	public void setOkulzumres(Set okulzumres) {
		this.okulzumres = okulzumres;
	}

}
