package com.Argeloji.Domain;

// default package
// Generated Mar 19, 2013 1:29:16 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Kazanim generated by hbm2java
 */
public class Kazanim implements java.io.Serializable {

	private int kod;
	private DersSinifAltOgrenmeAlani dersSinifAltOgrenmeAlani;
	private int sira;
	private String aciklama;
	private Set sorus = new HashSet(0);

	public Kazanim() {
	}

	public Kazanim(int kod, DersSinifAltOgrenmeAlani dersSinifAltOgrenmeAlani,
			int sira, String aciklama) {
		this.kod = kod;
		this.dersSinifAltOgrenmeAlani = dersSinifAltOgrenmeAlani;
		this.sira = sira;
		this.aciklama = aciklama;
	}

	public Kazanim(int kod, DersSinifAltOgrenmeAlani dersSinifAltOgrenmeAlani,
			int sira, String aciklama, Set sorus) {
		this.kod = kod;
		this.dersSinifAltOgrenmeAlani = dersSinifAltOgrenmeAlani;
		this.sira = sira;
		this.aciklama = aciklama;
		this.sorus = sorus;
	}

	public int getKod() {
		return this.kod;
	}

	public void setKod(int kod) {
		this.kod = kod;
	}

	public DersSinifAltOgrenmeAlani getDersSinifAltOgrenmeAlani() {
		return this.dersSinifAltOgrenmeAlani;
	}

	public void setDersSinifAltOgrenmeAlani(
			DersSinifAltOgrenmeAlani dersSinifAltOgrenmeAlani) {
		this.dersSinifAltOgrenmeAlani = dersSinifAltOgrenmeAlani;
	}

	public int getSira() {
		return this.sira;
	}

	public void setSira(int sira) {
		this.sira = sira;
	}

	public String getAciklama() {
		return this.aciklama;
	}

	public void setAciklama(String aciklama) {
		this.aciklama = aciklama;
	}

	public Set getSorus() {
		return this.sorus;
	}

	public void setSorus(Set sorus) {
		this.sorus = sorus;
	}

}
