package com.Argeloji.Domain;

// default package
// Generated Mar 18, 2013 10:44:04 AM by Hibernate Tools 3.4.0.CR1

/**
 * Klasik generated by hbm2java
 */
public class Klasik implements java.io.Serializable {

	private KlasikId id;
	private Soru soru;

	public Klasik() {
	}

	public Klasik(KlasikId id, Soru soru) {
		this.id = id;
		this.soru = soru;
	}

	public KlasikId getId() {
		return this.id;
	}

	public void setId(KlasikId id) {
		this.id = id;
	}

	public Soru getSoru() {
		return this.soru;
	}

	public void setSoru(Soru soru) {
		this.soru = soru;
	}

}
