package com.Argeloji.Domain;

// default package
// Generated Mar 18, 2013 10:44:04 AM by Hibernate Tools 3.4.0.CR1

/**
 * KlasikId generated by hbm2java
 */
public class KlasikId implements java.io.Serializable {

	private long soruKod;
	private String dogrucevap;

	public KlasikId() {
	}

	public KlasikId(long soruKod, String dogrucevap) {
		this.soruKod = soruKod;
		this.dogrucevap = dogrucevap;
	}

	public long getSoruKod() {
		return this.soruKod;
	}

	public void setSoruKod(long soruKod) {
		this.soruKod = soruKod;
	}

	public String getDogrucevap() {
		return this.dogrucevap;
	}

	public void setDogrucevap(String dogrucevap) {
		this.dogrucevap = dogrucevap;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof KlasikId))
			return false;
		KlasikId castOther = (KlasikId) other;

		return (this.getSoruKod() == castOther.getSoruKod())
				&& ((this.getDogrucevap() == castOther.getDogrucevap()) || (this
						.getDogrucevap() != null
						&& castOther.getDogrucevap() != null && this
						.getDogrucevap().equals(castOther.getDogrucevap())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getSoruKod();
		result = 37
				* result
				+ (getDogrucevap() == null ? 0 : this.getDogrucevap()
						.hashCode());
		return result;
	}

}
