package com.Argeloji.Domain;

// default package
// Generated Mar 18, 2013 10:44:04 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Kullanici generated by hbm2java
 */
public class Kullanici implements java.io.Serializable {

	private long kod;
	private Adres adres;
	private String ad;
	private String soyad;
	private int telefon;
	private Date giristarih;
	private String email;
	private Set useridmappers = new HashSet(0);
	private Set uygulamaKullanicis = new HashSet(0);
	private Set ogrencis = new HashSet(0);
	private Set velis = new HashSet(0);
	private Set personels = new HashSet(0);

	public Kullanici() {
	}

	public Kullanici(long kod, Adres adres, String ad, String soyad,
			int telefon, Date giristarih, String email) {
		this.kod = kod;
		this.adres = adres;
		this.ad = ad;
		this.soyad = soyad;
		this.telefon = telefon;
		this.giristarih = giristarih;
		this.email = email;
	}

	public Kullanici(long kod, Adres adres, String ad, String soyad,
			int telefon, Date giristarih, String email, Set useridmappers,
			Set uygulamaKullanicis, Set ogrencis, Set velis, Set personels) {
		this.kod = kod;
		this.adres = adres;
		this.ad = ad;
		this.soyad = soyad;
		this.telefon = telefon;
		this.giristarih = giristarih;
		this.email = email;
		this.useridmappers = useridmappers;
		this.uygulamaKullanicis = uygulamaKullanicis;
		this.ogrencis = ogrencis;
		this.velis = velis;
		this.personels = personels;
	}

	public long getKod() {
		return this.kod;
	}

	public void setKod(long kod) {
		this.kod = kod;
	}

	public Adres getAdres() {
		return this.adres;
	}

	public void setAdres(Adres adres) {
		this.adres = adres;
	}

	public String getAd() {
		return this.ad;
	}

	public void setAd(String ad) {
		this.ad = ad;
	}

	public String getSoyad() {
		return this.soyad;
	}

	public void setSoyad(String soyad) {
		this.soyad = soyad;
	}

	public int getTelefon() {
		return this.telefon;
	}

	public void setTelefon(int telefon) {
		this.telefon = telefon;
	}

	public Date getGiristarih() {
		return this.giristarih;
	}

	public void setGiristarih(Date giristarih) {
		this.giristarih = giristarih;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Set getUseridmappers() {
		return this.useridmappers;
	}

	public void setUseridmappers(Set useridmappers) {
		this.useridmappers = useridmappers;
	}

	public Set getUygulamaKullanicis() {
		return this.uygulamaKullanicis;
	}

	public void setUygulamaKullanicis(Set uygulamaKullanicis) {
		this.uygulamaKullanicis = uygulamaKullanicis;
	}

	public Set getOgrencis() {
		return this.ogrencis;
	}

	public void setOgrencis(Set ogrencis) {
		this.ogrencis = ogrencis;
	}

	public Set getVelis() {
		return this.velis;
	}

	public void setVelis(Set velis) {
		this.velis = velis;
	}

	public Set getPersonels() {
		return this.personels;
	}

	public void setPersonels(Set personels) {
		this.personels = personels;
	}

}
