package com.Argeloji.Domain;

// default package
// Generated Mar 18, 2013 10:44:04 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Kullanicigrup generated by hbm2java
 */
public class Kullanicigrup implements java.io.Serializable {

	private int kod;
	private String tip;
	private Set zumres = new HashSet(0);
	private Set yonetims = new HashSet(0);
	private Set oabs = new HashSet(0);

	public Kullanicigrup() {
	}

	public Kullanicigrup(int kod, String tip) {
		this.kod = kod;
		this.tip = tip;
	}

	public Kullanicigrup(int kod, String tip, Set zumres, Set yonetims, Set oabs) {
		this.kod = kod;
		this.tip = tip;
		this.zumres = zumres;
		this.yonetims = yonetims;
		this.oabs = oabs;
	}

	public int getKod() {
		return this.kod;
	}

	public void setKod(int kod) {
		this.kod = kod;
	}

	public String getTip() {
		return this.tip;
	}

	public void setTip(String tip) {
		this.tip = tip;
	}

	public Set getZumres() {
		return this.zumres;
	}

	public void setZumres(Set zumres) {
		this.zumres = zumres;
	}

	public Set getYonetims() {
		return this.yonetims;
	}

	public void setYonetims(Set yonetims) {
		this.yonetims = yonetims;
	}

	public Set getOabs() {
		return this.oabs;
	}

	public void setOabs(Set oabs) {
		this.oabs = oabs;
	}

}
