package com.Argeloji.Domain;

// default package
// Generated Mar 18, 2013 10:44:04 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * KulupogretmenId generated by hbm2java
 */
public class KulupogretmenId implements java.io.Serializable {

	private Date giristarih;
	private long kullaniciPersonelKod;
	private int okulkulupKod;

	public KulupogretmenId() {
	}

	public KulupogretmenId(Date giristarih, long kullaniciPersonelKod,
			int okulkulupKod) {
		this.giristarih = giristarih;
		this.kullaniciPersonelKod = kullaniciPersonelKod;
		this.okulkulupKod = okulkulupKod;
	}

	public Date getGiristarih() {
		return this.giristarih;
	}

	public void setGiristarih(Date giristarih) {
		this.giristarih = giristarih;
	}

	public long getKullaniciPersonelKod() {
		return this.kullaniciPersonelKod;
	}

	public void setKullaniciPersonelKod(long kullaniciPersonelKod) {
		this.kullaniciPersonelKod = kullaniciPersonelKod;
	}

	public int getOkulkulupKod() {
		return this.okulkulupKod;
	}

	public void setOkulkulupKod(int okulkulupKod) {
		this.okulkulupKod = okulkulupKod;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof KulupogretmenId))
			return false;
		KulupogretmenId castOther = (KulupogretmenId) other;

		return ((this.getGiristarih() == castOther.getGiristarih()) || (this
				.getGiristarih() != null && castOther.getGiristarih() != null && this
				.getGiristarih().equals(castOther.getGiristarih())))
				&& (this.getKullaniciPersonelKod() == castOther
						.getKullaniciPersonelKod())
				&& (this.getOkulkulupKod() == castOther.getOkulkulupKod());
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getGiristarih() == null ? 0 : this.getGiristarih()
						.hashCode());
		result = 37 * result + (int) this.getKullaniciPersonelKod();
		result = 37 * result + this.getOkulkulupKod();
		return result;
	}

}
