package com.Argeloji.Domain;

// default package
// Generated Mar 18, 2013 10:44:04 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Kulupogretmen generated by hbm2java
 */
public class Kulupogretmen implements java.io.Serializable {

	private KulupogretmenId id;
	private Okulkulup okulkulup;
	private Personel personel;
	private Date cikistarih;

	public Kulupogretmen() {
	}

	public Kulupogretmen(KulupogretmenId id, Okulkulup okulkulup,
			Personel personel, Date cikistarih) {
		this.id = id;
		this.okulkulup = okulkulup;
		this.personel = personel;
		this.cikistarih = cikistarih;
	}

	public KulupogretmenId getId() {
		return this.id;
	}

	public void setId(KulupogretmenId id) {
		this.id = id;
	}

	public Okulkulup getOkulkulup() {
		return this.okulkulup;
	}

	public void setOkulkulup(Okulkulup okulkulup) {
		this.okulkulup = okulkulup;
	}

	public Personel getPersonel() {
		return this.personel;
	}

	public void setPersonel(Personel personel) {
		this.personel = personel;
	}

	public Date getCikistarih() {
		return this.cikistarih;
	}

	public void setCikistarih(Date cikistarih) {
		this.cikistarih = cikistarih;
	}

}
