package com.Argeloji.Domain;

// default package
// Generated Mar 18, 2013 10:44:04 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Kulup generated by hbm2java
 */
public class Kulup implements java.io.Serializable {

	private int kod;
	private Kademe kademe;
	private String ad;
	private Set okulkulups = new HashSet(0);

	public Kulup() {
	}

	public Kulup(int kod, Kademe kademe, String ad) {
		this.kod = kod;
		this.kademe = kademe;
		this.ad = ad;
	}

	public Kulup(int kod, Kademe kademe, String ad, Set okulkulups) {
		this.kod = kod;
		this.kademe = kademe;
		this.ad = ad;
		this.okulkulups = okulkulups;
	}

	public int getKod() {
		return this.kod;
	}

	public void setKod(int kod) {
		this.kod = kod;
	}

	public Kademe getKademe() {
		return this.kademe;
	}

	public void setKademe(Kademe kademe) {
		this.kademe = kademe;
	}

	public String getAd() {
		return this.ad;
	}

	public void setAd(String ad) {
		this.ad = ad;
	}

	public Set getOkulkulups() {
		return this.okulkulups;
	}

	public void setOkulkulups(Set okulkulups) {
		this.okulkulups = okulkulups;
	}

}
