package com.Argeloji.Domain;

// default package
// Generated Mar 18, 2013 10:44:04 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * KulupogrenciId generated by hbm2java
 */
public class KulupogrenciId implements java.io.Serializable {

	private long kullaniciOgrenciKod;
	private Date giristarih;
	private int okulkulupKod;

	public KulupogrenciId() {
	}

	public KulupogrenciId(long kullaniciOgrenciKod, Date giristarih,
			int okulkulupKod) {
		this.kullaniciOgrenciKod = kullaniciOgrenciKod;
		this.giristarih = giristarih;
		this.okulkulupKod = okulkulupKod;
	}

	public long getKullaniciOgrenciKod() {
		return this.kullaniciOgrenciKod;
	}

	public void setKullaniciOgrenciKod(long kullaniciOgrenciKod) {
		this.kullaniciOgrenciKod = kullaniciOgrenciKod;
	}

	public Date getGiristarih() {
		return this.giristarih;
	}

	public void setGiristarih(Date giristarih) {
		this.giristarih = giristarih;
	}

	public int getOkulkulupKod() {
		return this.okulkulupKod;
	}

	public void setOkulkulupKod(int okulkulupKod) {
		this.okulkulupKod = okulkulupKod;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof KulupogrenciId))
			return false;
		KulupogrenciId castOther = (KulupogrenciId) other;

		return (this.getKullaniciOgrenciKod() == castOther
				.getKullaniciOgrenciKod())
				&& ((this.getGiristarih() == castOther.getGiristarih()) || (this
						.getGiristarih() != null
						&& castOther.getGiristarih() != null && this
						.getGiristarih().equals(castOther.getGiristarih())))
				&& (this.getOkulkulupKod() == castOther.getOkulkulupKod());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getKullaniciOgrenciKod();
		result = 37
				* result
				+ (getGiristarih() == null ? 0 : this.getGiristarih()
						.hashCode());
		result = 37 * result + this.getOkulkulupKod();
		return result;
	}

}
