package com.Argeloji.Domain;

// default package
// Generated Mar 18, 2013 10:44:04 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Kulupogrenci generated by hbm2java
 */
public class Kulupogrenci implements java.io.Serializable {

	private KulupogrenciId id;
	private Okulkulup okulkulup;
	private Ogrenci ogrenci;
	private Date cikistarih;

	public Kulupogrenci() {
	}

	public Kulupogrenci(KulupogrenciId id, Okulkulup okulkulup, Ogrenci ogrenci) {
		this.id = id;
		this.okulkulup = okulkulup;
		this.ogrenci = ogrenci;
	}

	public Kulupogrenci(KulupogrenciId id, Okulkulup okulkulup,
			Ogrenci ogrenci, Date cikistarih) {
		this.id = id;
		this.okulkulup = okulkulup;
		this.ogrenci = ogrenci;
		this.cikistarih = cikistarih;
	}

	public KulupogrenciId getId() {
		return this.id;
	}

	public void setId(KulupogrenciId id) {
		this.id = id;
	}

	public Okulkulup getOkulkulup() {
		return this.okulkulup;
	}

	public void setOkulkulup(Okulkulup okulkulup) {
		this.okulkulup = okulkulup;
	}

	public Ogrenci getOgrenci() {
		return this.ogrenci;
	}

	public void setOgrenci(Ogrenci ogrenci) {
		this.ogrenci = ogrenci;
	}

	public Date getCikistarih() {
		return this.cikistarih;
	}

	public void setCikistarih(Date cikistarih) {
		this.cikistarih = cikistarih;
	}

}
