package com.Argeloji.Domain;

// default package
// Generated Mar 18, 2013 10:44:04 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Labratuar generated by hbm2java
 */
public class Labratuar implements java.io.Serializable {

	private LabratuarId id;
	private Altyapi altyapi;
	private Date cikistarihi;
	private Date giristarihi;
	private int kapasite;
	private String labadi;

	public Labratuar() {
	}

	public Labratuar(LabratuarId id, Altyapi altyapi, Date cikistarihi,
			Date giristarihi, int kapasite, String labadi) {
		this.id = id;
		this.altyapi = altyapi;
		this.cikistarihi = cikistarihi;
		this.giristarihi = giristarihi;
		this.kapasite = kapasite;
		this.labadi = labadi;
	}

	public LabratuarId getId() {
		return this.id;
	}

	public void setId(LabratuarId id) {
		this.id = id;
	}

	public Altyapi getAltyapi() {
		return this.altyapi;
	}

	public void setAltyapi(Altyapi altyapi) {
		this.altyapi = altyapi;
	}

	public Date getCikistarihi() {
		return this.cikistarihi;
	}

	public void setCikistarihi(Date cikistarihi) {
		this.cikistarihi = cikistarihi;
	}

	public Date getGiristarihi() {
		return this.giristarihi;
	}

	public void setGiristarihi(Date giristarihi) {
		this.giristarihi = giristarihi;
	}

	public int getKapasite() {
		return this.kapasite;
	}

	public void setKapasite(int kapasite) {
		this.kapasite = kapasite;
	}

	public String getLabadi() {
		return this.labadi;
	}

	public void setLabadi(String labadi) {
		this.labadi = labadi;
	}

}
