package com.Argeloji.Domain;

// default package
// Generated Mar 18, 2013 10:44:04 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Oab generated by hbm2java
 */
public class Oab implements java.io.Serializable {

	private int kod;
	private Kullanicigrup kullanicigrup;
	private String ad;
	private Date giristarih;
	private Date cikistarih;
	private Set oabvelis = new HashSet(0);

	public Oab() {
	}

	public Oab(int kod, Kullanicigrup kullanicigrup, String ad,
			Date giristarih, Date cikistarih) {
		this.kod = kod;
		this.kullanicigrup = kullanicigrup;
		this.ad = ad;
		this.giristarih = giristarih;
		this.cikistarih = cikistarih;
	}

	public Oab(int kod, Kullanicigrup kullanicigrup, String ad,
			Date giristarih, Date cikistarih, Set oabvelis) {
		this.kod = kod;
		this.kullanicigrup = kullanicigrup;
		this.ad = ad;
		this.giristarih = giristarih;
		this.cikistarih = cikistarih;
		this.oabvelis = oabvelis;
	}

	public int getKod() {
		return this.kod;
	}

	public void setKod(int kod) {
		this.kod = kod;
	}

	public Kullanicigrup getKullanicigrup() {
		return this.kullanicigrup;
	}

	public void setKullanicigrup(Kullanicigrup kullanicigrup) {
		this.kullanicigrup = kullanicigrup;
	}

	public String getAd() {
		return this.ad;
	}

	public void setAd(String ad) {
		this.ad = ad;
	}

	public Date getGiristarih() {
		return this.giristarih;
	}

	public void setGiristarih(Date giristarih) {
		this.giristarih = giristarih;
	}

	public Date getCikistarih() {
		return this.cikistarih;
	}

	public void setCikistarih(Date cikistarih) {
		this.cikistarih = cikistarih;
	}

	public Set getOabvelis() {
		return this.oabvelis;
	}

	public void setOabvelis(Set oabvelis) {
		this.oabvelis = oabvelis;
	}

}
