package com.Argeloji.Domain;

// default package
// Generated Mar 18, 2013 10:44:04 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Oabveli generated by hbm2java
 */
public class Oabveli implements java.io.Serializable {

	private OabveliId id;
	private Oab oab;
	private Veli veli;
	private Date cikistarih;

	public Oabveli() {
	}

	public Oabveli(OabveliId id, Oab oab, Veli veli, Date cikistarih) {
		this.id = id;
		this.oab = oab;
		this.veli = veli;
		this.cikistarih = cikistarih;
	}

	public OabveliId getId() {
		return this.id;
	}

	public void setId(OabveliId id) {
		this.id = id;
	}

	public Oab getOab() {
		return this.oab;
	}

	public void setOab(Oab oab) {
		this.oab = oab;
	}

	public Veli getVeli() {
		return this.veli;
	}

	public void setVeli(Veli veli) {
		this.veli = veli;
	}

	public Date getCikistarih() {
		return this.cikistarih;
	}

	public void setCikistarih(Date cikistarih) {
		this.cikistarih = cikistarih;
	}

}
