package com.Argeloji.Domain;

// default package
// Generated Mar 18, 2013 10:44:04 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Ogrencisube generated by hbm2java
 */
public class Ogrencisube implements java.io.Serializable {

	private OgrencisubeId id;
	private Ogrenci ogrenci;
	private Okulsube okulsube;
	private Date cikiszaman;

	public Ogrencisube() {
	}

	public Ogrencisube(OgrencisubeId id, Ogrenci ogrenci, Okulsube okulsube,
			Date cikiszaman) {
		this.id = id;
		this.ogrenci = ogrenci;
		this.okulsube = okulsube;
		this.cikiszaman = cikiszaman;
	}

	public OgrencisubeId getId() {
		return this.id;
	}

	public void setId(OgrencisubeId id) {
		this.id = id;
	}

	public Ogrenci getOgrenci() {
		return this.ogrenci;
	}

	public void setOgrenci(Ogrenci ogrenci) {
		this.ogrenci = ogrenci;
	}

	public Okulsube getOkulsube() {
		return this.okulsube;
	}

	public void setOkulsube(Okulsube okulsube) {
		this.okulsube = okulsube;
	}

	public Date getCikiszaman() {
		return this.cikiszaman;
	}

	public void setCikiszaman(Date cikiszaman) {
		this.cikiszaman = cikiszaman;
	}

}
