package com.Argeloji.Domain;

// default package
// Generated Mar 18, 2013 10:44:04 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * OgrencisubeId generated by hbm2java
 */
public class OgrencisubeId implements java.io.Serializable {

	private long kullaniciOgrenciKod;
	private Date giriszaman;
	private int okulsubeKod;

	public OgrencisubeId() {
	}

	public OgrencisubeId(long kullaniciOgrenciKod, Date giriszaman,
			int okulsubeKod) {
		this.kullaniciOgrenciKod = kullaniciOgrenciKod;
		this.giriszaman = giriszaman;
		this.okulsubeKod = okulsubeKod;
	}

	public long getKullaniciOgrenciKod() {
		return this.kullaniciOgrenciKod;
	}

	public void setKullaniciOgrenciKod(long kullaniciOgrenciKod) {
		this.kullaniciOgrenciKod = kullaniciOgrenciKod;
	}

	public Date getGiriszaman() {
		return this.giriszaman;
	}

	public void setGiriszaman(Date giriszaman) {
		this.giriszaman = giriszaman;
	}

	public int getOkulsubeKod() {
		return this.okulsubeKod;
	}

	public void setOkulsubeKod(int okulsubeKod) {
		this.okulsubeKod = okulsubeKod;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof OgrencisubeId))
			return false;
		OgrencisubeId castOther = (OgrencisubeId) other;

		return (this.getKullaniciOgrenciKod() == castOther
				.getKullaniciOgrenciKod())
				&& ((this.getGiriszaman() == castOther.getGiriszaman()) || (this
						.getGiriszaman() != null
						&& castOther.getGiriszaman() != null && this
						.getGiriszaman().equals(castOther.getGiriszaman())))
				&& (this.getOkulsubeKod() == castOther.getOkulsubeKod());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getKullaniciOgrenciKod();
		result = 37
				* result
				+ (getGiriszaman() == null ? 0 : this.getGiriszaman()
						.hashCode());
		result = 37 * result + this.getOkulsubeKod();
		return result;
	}

}
