package com.Argeloji.Domain;

// default package
// Generated Mar 18, 2013 10:44:04 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * OgrenmeAlani generated by hbm2java
 */
public class OgrenmeAlani implements java.io.Serializable {

	private int kod;
	private String ad;
	private Set altOgrenmeAlanis = new HashSet(0);

	public OgrenmeAlani() {
	}

	public OgrenmeAlani(int kod, String ad) {
		this.kod = kod;
		this.ad = ad;
	}

	public OgrenmeAlani(int kod, String ad, Set altOgrenmeAlanis) {
		this.kod = kod;
		this.ad = ad;
		this.altOgrenmeAlanis = altOgrenmeAlanis;
	}

	public int getKod() {
		return this.kod;
	}

	public void setKod(int kod) {
		this.kod = kod;
	}

	public String getAd() {
		return this.ad;
	}

	public void setAd(String ad) {
		this.ad = ad;
	}

	public Set getAltOgrenmeAlanis() {
		return this.altOgrenmeAlanis;
	}

	public void setAltOgrenmeAlanis(Set altOgrenmeAlanis) {
		this.altOgrenmeAlanis = altOgrenmeAlanis;
	}

}
