package com.Argeloji.Domain;

// default package
// Generated Mar 18, 2013 10:44:04 AM by Hibernate Tools 3.4.0.CR1

/**
 * Okulgrubu generated by hbm2java
 */
public class Okulgrubu implements java.io.Serializable {

	private OkulgrubuId id;
	private Ozelokul ozelokul;
	private Okul okul;

	public Okulgrubu() {
	}

	public Okulgrubu(OkulgrubuId id, Ozelokul ozelokul, Okul okul) {
		this.id = id;
		this.ozelokul = ozelokul;
		this.okul = okul;
	}

	public OkulgrubuId getId() {
		return this.id;
	}

	public void setId(OkulgrubuId id) {
		this.id = id;
	}

	public Ozelokul getOzelokul() {
		return this.ozelokul;
	}

	public void setOzelokul(Ozelokul ozelokul) {
		this.ozelokul = ozelokul;
	}

	public Okul getOkul() {
		return this.okul;
	}

	public void setOkul(Okul okul) {
		this.okul = okul;
	}

}
