package com.Argeloji.Domain;

// default package
// Generated Mar 18, 2013 10:44:04 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * OkulkademeId generated by hbm2java
 */
public class OkulkademeId implements java.io.Serializable {

	private int kademeKod;
	private Date giristarih;
	private int okulKod;

	public OkulkademeId() {
	}

	public OkulkademeId(int kademeKod, Date giristarih, int okulKod) {
		this.kademeKod = kademeKod;
		this.giristarih = giristarih;
		this.okulKod = okulKod;
	}

	public int getKademeKod() {
		return this.kademeKod;
	}

	public void setKademeKod(int kademeKod) {
		this.kademeKod = kademeKod;
	}

	public Date getGiristarih() {
		return this.giristarih;
	}

	public void setGiristarih(Date giristarih) {
		this.giristarih = giristarih;
	}

	public int getOkulKod() {
		return this.okulKod;
	}

	public void setOkulKod(int okulKod) {
		this.okulKod = okulKod;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof OkulkademeId))
			return false;
		OkulkademeId castOther = (OkulkademeId) other;

		return (this.getKademeKod() == castOther.getKademeKod())
				&& ((this.getGiristarih() == castOther.getGiristarih()) || (this
						.getGiristarih() != null
						&& castOther.getGiristarih() != null && this
						.getGiristarih().equals(castOther.getGiristarih())))
				&& (this.getOkulKod() == castOther.getOkulKod());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getKademeKod();
		result = 37
				* result
				+ (getGiristarih() == null ? 0 : this.getGiristarih()
						.hashCode());
		result = 37 * result + this.getOkulKod();
		return result;
	}

}
