package com.Argeloji.Domain;

// default package
// Generated Mar 18, 2013 10:44:04 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * OkulpersonelId generated by hbm2java
 */
public class OkulpersonelId implements java.io.Serializable {

	private long kullaniciPersonelKod;
	private Date giristarih;
	private int okulKod;

	public OkulpersonelId() {
	}

	public OkulpersonelId(long kullaniciPersonelKod, Date giristarih,
			int okulKod) {
		this.kullaniciPersonelKod = kullaniciPersonelKod;
		this.giristarih = giristarih;
		this.okulKod = okulKod;
	}

	public long getKullaniciPersonelKod() {
		return this.kullaniciPersonelKod;
	}

	public void setKullaniciPersonelKod(long kullaniciPersonelKod) {
		this.kullaniciPersonelKod = kullaniciPersonelKod;
	}

	public Date getGiristarih() {
		return this.giristarih;
	}

	public void setGiristarih(Date giristarih) {
		this.giristarih = giristarih;
	}

	public int getOkulKod() {
		return this.okulKod;
	}

	public void setOkulKod(int okulKod) {
		this.okulKod = okulKod;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof OkulpersonelId))
			return false;
		OkulpersonelId castOther = (OkulpersonelId) other;

		return (this.getKullaniciPersonelKod() == castOther
				.getKullaniciPersonelKod())
				&& ((this.getGiristarih() == castOther.getGiristarih()) || (this
						.getGiristarih() != null
						&& castOther.getGiristarih() != null && this
						.getGiristarih().equals(castOther.getGiristarih())))
				&& (this.getOkulKod() == castOther.getOkulKod());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getKullaniciPersonelKod();
		result = 37
				* result
				+ (getGiristarih() == null ? 0 : this.getGiristarih()
						.hashCode());
		result = 37 * result + this.getOkulKod();
		return result;
	}

}
