package com.Argeloji.Domain;

// default package
// Generated Mar 18, 2013 10:44:04 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Okulpersonel generated by hbm2java
 */
public class Okulpersonel implements java.io.Serializable {

	private OkulpersonelId id;
	private Okul okul;
	private Personel personel;
	private Date cikistarih;

	public Okulpersonel() {
	}

	public Okulpersonel(OkulpersonelId id, Okul okul, Personel personel,
			Date cikistarih) {
		this.id = id;
		this.okul = okul;
		this.personel = personel;
		this.cikistarih = cikistarih;
	}

	public OkulpersonelId getId() {
		return this.id;
	}

	public void setId(OkulpersonelId id) {
		this.id = id;
	}

	public Okul getOkul() {
		return this.okul;
	}

	public void setOkul(Okul okul) {
		this.okul = okul;
	}

	public Personel getPersonel() {
		return this.personel;
	}

	public void setPersonel(Personel personel) {
		this.personel = personel;
	}

	public Date getCikistarih() {
		return this.cikistarih;
	}

	public void setCikistarih(Date cikistarih) {
		this.cikistarih = cikistarih;
	}

}
