package com.Argeloji.Domain;

// default package
// Generated Mar 18, 2013 10:44:04 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Okulsube generated by hbm2java
 */
public class Okulsube implements java.io.Serializable {

	private int kod;
	private Sube sube;
	private Okul okul;
	private Date giristarih;
	private Date cikistarih;
	private Set ogrencisubes = new HashSet(0);

	public Okulsube() {
	}

	public Okulsube(int kod, Sube sube, Okul okul, Date giristarih,
			Date cikistarih) {
		this.kod = kod;
		this.sube = sube;
		this.okul = okul;
		this.giristarih = giristarih;
		this.cikistarih = cikistarih;
	}

	public Okulsube(int kod, Sube sube, Okul okul, Date giristarih,
			Date cikistarih, Set ogrencisubes) {
		this.kod = kod;
		this.sube = sube;
		this.okul = okul;
		this.giristarih = giristarih;
		this.cikistarih = cikistarih;
		this.ogrencisubes = ogrencisubes;
	}

	public int getKod() {
		return this.kod;
	}

	public void setKod(int kod) {
		this.kod = kod;
	}

	public Sube getSube() {
		return this.sube;
	}

	public void setSube(Sube sube) {
		this.sube = sube;
	}

	public Okul getOkul() {
		return this.okul;
	}

	public void setOkul(Okul okul) {
		this.okul = okul;
	}

	public Date getGiristarih() {
		return this.giristarih;
	}

	public void setGiristarih(Date giristarih) {
		this.giristarih = giristarih;
	}

	public Date getCikistarih() {
		return this.cikistarih;
	}

	public void setCikistarih(Date cikistarih) {
		this.cikistarih = cikistarih;
	}

	public Set getOgrencisubes() {
		return this.ogrencisubes;
	}

	public void setOgrencisubes(Set ogrencisubes) {
		this.ogrencisubes = ogrencisubes;
	}

}
