package com.Argeloji.Domain;

// default package
// Generated Mar 18, 2013 10:44:04 AM by Hibernate Tools 3.4.0.CR1

/**
 * OkulgrubuId generated by hbm2java
 */
public class OkulgrubuId implements java.io.Serializable {

	private int ozelokulKod;
	private int okulKod;

	public OkulgrubuId() {
	}

	public OkulgrubuId(int ozelokulKod, int okulKod) {
		this.ozelokulKod = ozelokulKod;
		this.okulKod = okulKod;
	}

	public int getOzelokulKod() {
		return this.ozelokulKod;
	}

	public void setOzelokulKod(int ozelokulKod) {
		this.ozelokulKod = ozelokulKod;
	}

	public int getOkulKod() {
		return this.okulKod;
	}

	public void setOkulKod(int okulKod) {
		this.okulKod = okulKod;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof OkulgrubuId))
			return false;
		OkulgrubuId castOther = (OkulgrubuId) other;

		return (this.getOzelokulKod() == castOther.getOzelokulKod())
				&& (this.getOkulKod() == castOther.getOkulKod());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getOzelokulKod();
		result = 37 * result + this.getOkulKod();
		return result;
	}

}
