package com.Argeloji.Domain;

// default package
// Generated Mar 18, 2013 10:44:04 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Okulkademe generated by hbm2java
 */
public class Okulkademe implements java.io.Serializable {

	private OkulkademeId id;
	private Okul okul;
	private Kademe kademe;
	private Date cikistarih;

	public Okulkademe() {
	}

	public Okulkademe(OkulkademeId id, Okul okul, Kademe kademe, Date cikistarih) {
		this.id = id;
		this.okul = okul;
		this.kademe = kademe;
		this.cikistarih = cikistarih;
	}

	public OkulkademeId getId() {
		return this.id;
	}

	public void setId(OkulkademeId id) {
		this.id = id;
	}

	public Okul getOkul() {
		return this.okul;
	}

	public void setOkul(Okul okul) {
		this.okul = okul;
	}

	public Kademe getKademe() {
		return this.kademe;
	}

	public void setKademe(Kademe kademe) {
		this.kademe = kademe;
	}

	public Date getCikistarih() {
		return this.cikistarih;
	}

	public void setCikistarih(Date cikistarih) {
		this.cikistarih = cikistarih;
	}

}
