package com.Argeloji.Domain;

// default package
// Generated Mar 18, 2013 10:44:04 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Okul generated by hbm2java
 */
public class Okul implements java.io.Serializable {

	private int kod;
	private Adres adres;
	private String ad;
	private Date giristarih;
	private String tip;
	private Set okulogrencis = new HashSet(0);
	private Set okulgrubus = new HashSet(0);
	private Set okulkulups = new HashSet(0);
	private Set okulzumres = new HashSet(0);
	private Set okulpersonels = new HashSet(0);
	private Set okulsubes = new HashSet(0);
	private Set okulaltyapis = new HashSet(0);
	private Set okulkademes = new HashSet(0);
	private Set veliokuls = new HashSet(0);
	private Set groups = new HashSet(0);

	public Okul() {
	}

	public Okul(int kod, Adres adres, String ad, Date giristarih, String tip) {
		this.kod = kod;
		this.adres = adres;
		this.ad = ad;
		this.giristarih = giristarih;
		this.tip = tip;
	}

	public Okul(int kod, Adres adres, String ad, Date giristarih, String tip,
			Set okulogrencis, Set okulgrubus, Set okulkulups, Set okulzumres,
			Set okulpersonels, Set okulsubes, Set okulaltyapis,
			Set okulkademes, Set veliokuls, Set groups) {
		this.kod = kod;
		this.adres = adres;
		this.ad = ad;
		this.giristarih = giristarih;
		this.tip = tip;
		this.okulogrencis = okulogrencis;
		this.okulgrubus = okulgrubus;
		this.okulkulups = okulkulups;
		this.okulzumres = okulzumres;
		this.okulpersonels = okulpersonels;
		this.okulsubes = okulsubes;
		this.okulaltyapis = okulaltyapis;
		this.okulkademes = okulkademes;
		this.veliokuls = veliokuls;
		this.groups = groups;
	}

	public int getKod() {
		return this.kod;
	}

	public void setKod(int kod) {
		this.kod = kod;
	}

	public Adres getAdres() {
		return this.adres;
	}

	public void setAdres(Adres adres) {
		this.adres = adres;
	}

	public String getAd() {
		return this.ad;
	}

	public void setAd(String ad) {
		this.ad = ad;
	}

	public Date getGiristarih() {
		return this.giristarih;
	}

	public void setGiristarih(Date giristarih) {
		this.giristarih = giristarih;
	}

	public String getTip() {
		return this.tip;
	}

	public void setTip(String tip) {
		this.tip = tip;
	}

	public Set getOkulogrencis() {
		return this.okulogrencis;
	}

	public void setOkulogrencis(Set okulogrencis) {
		this.okulogrencis = okulogrencis;
	}

	public Set getOkulgrubus() {
		return this.okulgrubus;
	}

	public void setOkulgrubus(Set okulgrubus) {
		this.okulgrubus = okulgrubus;
	}

	public Set getOkulkulups() {
		return this.okulkulups;
	}

	public void setOkulkulups(Set okulkulups) {
		this.okulkulups = okulkulups;
	}

	public Set getOkulzumres() {
		return this.okulzumres;
	}

	public void setOkulzumres(Set okulzumres) {
		this.okulzumres = okulzumres;
	}

	public Set getOkulpersonels() {
		return this.okulpersonels;
	}

	public void setOkulpersonels(Set okulpersonels) {
		this.okulpersonels = okulpersonels;
	}

	public Set getOkulsubes() {
		return this.okulsubes;
	}

	public void setOkulsubes(Set okulsubes) {
		this.okulsubes = okulsubes;
	}

	public Set getOkulaltyapis() {
		return this.okulaltyapis;
	}

	public void setOkulaltyapis(Set okulaltyapis) {
		this.okulaltyapis = okulaltyapis;
	}

	public Set getOkulkademes() {
		return this.okulkademes;
	}

	public void setOkulkademes(Set okulkademes) {
		this.okulkademes = okulkademes;
	}

	public Set getVeliokuls() {
		return this.veliokuls;
	}

	public void setVeliokuls(Set veliokuls) {
		this.veliokuls = veliokuls;
	}

	public Set getGroups() {
		return this.groups;
	}

	public void setGroups(Set groups) {
		this.groups = groups;
	}

}
