package com.Argeloji.Domain;

// default package
// Generated Mar 18, 2013 10:44:04 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Okulzumre generated by hbm2java
 */
public class Okulzumre implements java.io.Serializable {

	private OkulzumreId id;
	private Okul okul;
	private Zumre zumre;
	private Kademe kademe;
	private Date cikistarih;

	public Okulzumre() {
	}

	public Okulzumre(OkulzumreId id, Okul okul, Zumre zumre, Kademe kademe,
			Date cikistarih) {
		this.id = id;
		this.okul = okul;
		this.zumre = zumre;
		this.kademe = kademe;
		this.cikistarih = cikistarih;
	}

	public OkulzumreId getId() {
		return this.id;
	}

	public void setId(OkulzumreId id) {
		this.id = id;
	}

	public Okul getOkul() {
		return this.okul;
	}

	public void setOkul(Okul okul) {
		this.okul = okul;
	}

	public Zumre getZumre() {
		return this.zumre;
	}

	public void setZumre(Zumre zumre) {
		this.zumre = zumre;
	}

	public Kademe getKademe() {
		return this.kademe;
	}

	public void setKademe(Kademe kademe) {
		this.kademe = kademe;
	}

	public Date getCikistarih() {
		return this.cikistarih;
	}

	public void setCikistarih(Date cikistarih) {
		this.cikistarih = cikistarih;
	}

}
