package com.Argeloji.Domain;

// default package
// Generated Mar 18, 2013 10:44:04 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Okulkulup generated by hbm2java
 */
public class Okulkulup implements java.io.Serializable {

	private int kod;
	private Kulup kulup;
	private Okul okul;
	private Date giristarih;
	private Date cikistarih;
	private Set kulupogrencis = new HashSet(0);
	private Set kulupogretmens = new HashSet(0);

	public Okulkulup() {
	}

	public Okulkulup(int kod, Kulup kulup, Okul okul, Date giristarih,
			Date cikistarih) {
		this.kod = kod;
		this.kulup = kulup;
		this.okul = okul;
		this.giristarih = giristarih;
		this.cikistarih = cikistarih;
	}

	public Okulkulup(int kod, Kulup kulup, Okul okul, Date giristarih,
			Date cikistarih, Set kulupogrencis, Set kulupogretmens) {
		this.kod = kod;
		this.kulup = kulup;
		this.okul = okul;
		this.giristarih = giristarih;
		this.cikistarih = cikistarih;
		this.kulupogrencis = kulupogrencis;
		this.kulupogretmens = kulupogretmens;
	}

	public int getKod() {
		return this.kod;
	}

	public void setKod(int kod) {
		this.kod = kod;
	}

	public Kulup getKulup() {
		return this.kulup;
	}

	public void setKulup(Kulup kulup) {
		this.kulup = kulup;
	}

	public Okul getOkul() {
		return this.okul;
	}

	public void setOkul(Okul okul) {
		this.okul = okul;
	}

	public Date getGiristarih() {
		return this.giristarih;
	}

	public void setGiristarih(Date giristarih) {
		this.giristarih = giristarih;
	}

	public Date getCikistarih() {
		return this.cikistarih;
	}

	public void setCikistarih(Date cikistarih) {
		this.cikistarih = cikistarih;
	}

	public Set getKulupogrencis() {
		return this.kulupogrencis;
	}

	public void setKulupogrencis(Set kulupogrencis) {
		this.kulupogrencis = kulupogrencis;
	}

	public Set getKulupogretmens() {
		return this.kulupogretmens;
	}

	public void setKulupogretmens(Set kulupogretmens) {
		this.kulupogretmens = kulupogretmens;
	}

}
