package com.Argeloji.Domain;

// default package
// Generated Mar 18, 2013 10:44:04 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Okulogrenci generated by hbm2java
 */
public class Okulogrenci implements java.io.Serializable {

	private OkulogrenciId id;
	private Ogrenci ogrenci;
	private Okul okul;
	private Date cikistarih;
	private int ogrencino;

	public Okulogrenci() {
	}

	public Okulogrenci(OkulogrenciId id, Ogrenci ogrenci, Okul okul,
			Date cikistarih, int ogrencino) {
		this.id = id;
		this.ogrenci = ogrenci;
		this.okul = okul;
		this.cikistarih = cikistarih;
		this.ogrencino = ogrencino;
	}

	public OkulogrenciId getId() {
		return this.id;
	}

	public void setId(OkulogrenciId id) {
		this.id = id;
	}

	public Ogrenci getOgrenci() {
		return this.ogrenci;
	}

	public void setOgrenci(Ogrenci ogrenci) {
		this.ogrenci = ogrenci;
	}

	public Okul getOkul() {
		return this.okul;
	}

	public void setOkul(Okul okul) {
		this.okul = okul;
	}

	public Date getCikistarih() {
		return this.cikistarih;
	}

	public void setCikistarih(Date cikistarih) {
		this.cikistarih = cikistarih;
	}

	public int getOgrencino() {
		return this.ogrencino;
	}

	public void setOgrencino(int ogrencino) {
		this.ogrencino = ogrencino;
	}

}
