package com.Argeloji.Domain;

// default package
// Generated Mar 18, 2013 10:44:04 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * OkulogrenciId generated by hbm2java
 */
public class OkulogrenciId implements java.io.Serializable {

	private long kullaniciOgrenciKod;
	private Date giristarih;
	private int okulKod;

	public OkulogrenciId() {
	}

	public OkulogrenciId(long kullaniciOgrenciKod, Date giristarih, int okulKod) {
		this.kullaniciOgrenciKod = kullaniciOgrenciKod;
		this.giristarih = giristarih;
		this.okulKod = okulKod;
	}

	public long getKullaniciOgrenciKod() {
		return this.kullaniciOgrenciKod;
	}

	public void setKullaniciOgrenciKod(long kullaniciOgrenciKod) {
		this.kullaniciOgrenciKod = kullaniciOgrenciKod;
	}

	public Date getGiristarih() {
		return this.giristarih;
	}

	public void setGiristarih(Date giristarih) {
		this.giristarih = giristarih;
	}

	public int getOkulKod() {
		return this.okulKod;
	}

	public void setOkulKod(int okulKod) {
		this.okulKod = okulKod;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof OkulogrenciId))
			return false;
		OkulogrenciId castOther = (OkulogrenciId) other;

		return (this.getKullaniciOgrenciKod() == castOther
				.getKullaniciOgrenciKod())
				&& ((this.getGiristarih() == castOther.getGiristarih()) || (this
						.getGiristarih() != null
						&& castOther.getGiristarih() != null && this
						.getGiristarih().equals(castOther.getGiristarih())))
				&& (this.getOkulKod() == castOther.getOkulKod());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getKullaniciOgrenciKod();
		result = 37
				* result
				+ (getGiristarih() == null ? 0 : this.getGiristarih()
						.hashCode());
		result = 37 * result + this.getOkulKod();
		return result;
	}

}
