package com.Argeloji.Domain;

// default package
// Generated Mar 18, 2013 10:44:04 AM by Hibernate Tools 3.4.0.CR1

/**
 * OkulaltyapiId generated by hbm2java
 */
public class OkulaltyapiId implements java.io.Serializable {

	private int altyapiKod;
	private int okulKod;

	public OkulaltyapiId() {
	}

	public OkulaltyapiId(int altyapiKod, int okulKod) {
		this.altyapiKod = altyapiKod;
		this.okulKod = okulKod;
	}

	public int getAltyapiKod() {
		return this.altyapiKod;
	}

	public void setAltyapiKod(int altyapiKod) {
		this.altyapiKod = altyapiKod;
	}

	public int getOkulKod() {
		return this.okulKod;
	}

	public void setOkulKod(int okulKod) {
		this.okulKod = okulKod;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof OkulaltyapiId))
			return false;
		OkulaltyapiId castOther = (OkulaltyapiId) other;

		return (this.getAltyapiKod() == castOther.getAltyapiKod())
				&& (this.getOkulKod() == castOther.getOkulKod());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getAltyapiKod();
		result = 37 * result + this.getOkulKod();
		return result;
	}

}
