package com.Argeloji.Domain;

// default package
// Generated Mar 18, 2013 10:44:04 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * OturumSetSoruOlcmeCoktansecmeliTekcevap generated by hbm2java
 */
public class OturumSetSoruOlcmeCoktansecmeliTekcevap implements
		java.io.Serializable {

	private OturumSetSoruOlcmeCoktansecmeliTekcevapId id;
	private SetSoru setSoru;
	private Cihaz cihaz;
	private Cevapdurum cevapdurum;
	private short tercih1;
	private short tercih2;
	private short deneme;
	private Date giris;
	private Date cikis;
	private int sure;

	public OturumSetSoruOlcmeCoktansecmeliTekcevap() {
	}

	public OturumSetSoruOlcmeCoktansecmeliTekcevap(
			OturumSetSoruOlcmeCoktansecmeliTekcevapId id, SetSoru setSoru,
			Cihaz cihaz, Cevapdurum cevapdurum, short tercih1, short tercih2,
			short deneme, Date giris, Date cikis, int sure) {
		this.id = id;
		this.setSoru = setSoru;
		this.cihaz = cihaz;
		this.cevapdurum = cevapdurum;
		this.tercih1 = tercih1;
		this.tercih2 = tercih2;
		this.deneme = deneme;
		this.giris = giris;
		this.cikis = cikis;
		this.sure = sure;
	}

	public OturumSetSoruOlcmeCoktansecmeliTekcevapId getId() {
		return this.id;
	}

	public void setId(OturumSetSoruOlcmeCoktansecmeliTekcevapId id) {
		this.id = id;
	}

	public SetSoru getSetSoru() {
		return this.setSoru;
	}

	public void setSetSoru(SetSoru setSoru) {
		this.setSoru = setSoru;
	}

	public Cihaz getCihaz() {
		return this.cihaz;
	}

	public void setCihaz(Cihaz cihaz) {
		this.cihaz = cihaz;
	}

	public Cevapdurum getCevapdurum() {
		return this.cevapdurum;
	}

	public void setCevapdurum(Cevapdurum cevapdurum) {
		this.cevapdurum = cevapdurum;
	}

	public short getTercih1() {
		return this.tercih1;
	}

	public void setTercih1(short tercih1) {
		this.tercih1 = tercih1;
	}

	public short getTercih2() {
		return this.tercih2;
	}

	public void setTercih2(short tercih2) {
		this.tercih2 = tercih2;
	}

	public short getDeneme() {
		return this.deneme;
	}

	public void setDeneme(short deneme) {
		this.deneme = deneme;
	}

	public Date getGiris() {
		return this.giris;
	}

	public void setGiris(Date giris) {
		this.giris = giris;
	}

	public Date getCikis() {
		return this.cikis;
	}

	public void setCikis(Date cikis) {
		this.cikis = cikis;
	}

	public int getSure() {
		return this.sure;
	}

	public void setSure(int sure) {
		this.sure = sure;
	}

}
