package com.Argeloji.Domain;

// default package
// Generated Mar 18, 2013 10:44:04 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * OturumSetSoruOlcmeKlasik generated by hbm2java
 */
public class OturumSetSoruOlcmeKlasik implements java.io.Serializable {

	private OturumSetSoruOlcmeKlasikId id;
	private SetSoru setSoru;
	private Cihaz cihaz;
	private Cevapdurum cevapdurum;
	private String cevap1;
	private String cevap2;
	private short deneme;
	private Date giris;
	private Date cikis;
	private int sure;

	public OturumSetSoruOlcmeKlasik() {
	}

	public OturumSetSoruOlcmeKlasik(OturumSetSoruOlcmeKlasikId id,
			SetSoru setSoru, Cihaz cihaz, Cevapdurum cevapdurum, String cevap1,
			String cevap2, short deneme, Date giris, Date cikis, int sure) {
		this.id = id;
		this.setSoru = setSoru;
		this.cihaz = cihaz;
		this.cevapdurum = cevapdurum;
		this.cevap1 = cevap1;
		this.cevap2 = cevap2;
		this.deneme = deneme;
		this.giris = giris;
		this.cikis = cikis;
		this.sure = sure;
	}

	public OturumSetSoruOlcmeKlasikId getId() {
		return this.id;
	}

	public void setId(OturumSetSoruOlcmeKlasikId id) {
		this.id = id;
	}

	public SetSoru getSetSoru() {
		return this.setSoru;
	}

	public void setSetSoru(SetSoru setSoru) {
		this.setSoru = setSoru;
	}

	public Cihaz getCihaz() {
		return this.cihaz;
	}

	public void setCihaz(Cihaz cihaz) {
		this.cihaz = cihaz;
	}

	public Cevapdurum getCevapdurum() {
		return this.cevapdurum;
	}

	public void setCevapdurum(Cevapdurum cevapdurum) {
		this.cevapdurum = cevapdurum;
	}

	public String getCevap1() {
		return this.cevap1;
	}

	public void setCevap1(String cevap1) {
		this.cevap1 = cevap1;
	}

	public String getCevap2() {
		return this.cevap2;
	}

	public void setCevap2(String cevap2) {
		this.cevap2 = cevap2;
	}

	public short getDeneme() {
		return this.deneme;
	}

	public void setDeneme(short deneme) {
		this.deneme = deneme;
	}

	public Date getGiris() {
		return this.giris;
	}

	public void setGiris(Date giris) {
		this.giris = giris;
	}

	public Date getCikis() {
		return this.cikis;
	}

	public void setCikis(Date cikis) {
		this.cikis = cikis;
	}

	public int getSure() {
		return this.sure;
	}

	public void setSure(int sure) {
		this.sure = sure;
	}

}
