package com.Argeloji.Domain;

// default package
// Generated Mar 18, 2013 10:44:04 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Personel generated by hbm2java
 */
public class Personel implements java.io.Serializable {

	private long kullaniciKod;
	private Kullanici kullanici;
	private Set okulpersonels = new HashSet(0);
	private Set yonetimpersonels = new HashSet(0);
	private Set kulupogretmens = new HashSet(0);
	private Set zumreogretmens = new HashSet(0);
	private Set idaris = new HashSet(0);
	private Set akademiks = new HashSet(0);

	public Personel() {
	}

	public Personel(long kullaniciKod, Kullanici kullanici) {
		this.kullaniciKod = kullaniciKod;
		this.kullanici = kullanici;
	}

	public Personel(long kullaniciKod, Kullanici kullanici, Set okulpersonels,
			Set yonetimpersonels, Set kulupogretmens, Set zumreogretmens,
			Set idaris, Set akademiks) {
		this.kullaniciKod = kullaniciKod;
		this.kullanici = kullanici;
		this.okulpersonels = okulpersonels;
		this.yonetimpersonels = yonetimpersonels;
		this.kulupogretmens = kulupogretmens;
		this.zumreogretmens = zumreogretmens;
		this.idaris = idaris;
		this.akademiks = akademiks;
	}

	public long getKullaniciKod() {
		return this.kullaniciKod;
	}

	public void setKullaniciKod(long kullaniciKod) {
		this.kullaniciKod = kullaniciKod;
	}

	public Kullanici getKullanici() {
		return this.kullanici;
	}

	public void setKullanici(Kullanici kullanici) {
		this.kullanici = kullanici;
	}

	public Set getOkulpersonels() {
		return this.okulpersonels;
	}

	public void setOkulpersonels(Set okulpersonels) {
		this.okulpersonels = okulpersonels;
	}

	public Set getYonetimpersonels() {
		return this.yonetimpersonels;
	}

	public void setYonetimpersonels(Set yonetimpersonels) {
		this.yonetimpersonels = yonetimpersonels;
	}

	public Set getKulupogretmens() {
		return this.kulupogretmens;
	}

	public void setKulupogretmens(Set kulupogretmens) {
		this.kulupogretmens = kulupogretmens;
	}

	public Set getZumreogretmens() {
		return this.zumreogretmens;
	}

	public void setZumreogretmens(Set zumreogretmens) {
		this.zumreogretmens = zumreogretmens;
	}

	public Set getIdaris() {
		return this.idaris;
	}

	public void setIdaris(Set idaris) {
		this.idaris = idaris;
	}

	public Set getAkademiks() {
		return this.akademiks;
	}

	public void setAkademiks(Set akademiks) {
		this.akademiks = akademiks;
	}

}
