package com.Argeloji.Domain;

// default package
// Generated Mar 18, 2013 10:44:04 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * SetSoru generated by hbm2java
 */
public class SetSoru implements java.io.Serializable {

	private SetSoruId id;
	private Soru soru;
	private Sett sett;
	private short sira;
	private Set oturumSetSoruOlcmeCoktansecmeliTekcevaps = new HashSet(0);
	private Set oturumSetSoruOlcmeKlasiks = new HashSet(0);
	private Set oturumSetSoruOlcmeDogruyanlises = new HashSet(0);

	public SetSoru() {
	}

	public SetSoru(SetSoruId id, Soru soru, Sett sett, short sira) {
		this.id = id;
		this.soru = soru;
		this.sett = sett;
		this.sira = sira;
	}

	public SetSoru(SetSoruId id, Soru soru, Sett sett, short sira,
			Set oturumSetSoruOlcmeCoktansecmeliTekcevaps,
			Set oturumSetSoruOlcmeKlasiks, Set oturumSetSoruOlcmeDogruyanlises) {
		this.id = id;
		this.soru = soru;
		this.sett = sett;
		this.sira = sira;
		this.oturumSetSoruOlcmeCoktansecmeliTekcevaps = oturumSetSoruOlcmeCoktansecmeliTekcevaps;
		this.oturumSetSoruOlcmeKlasiks = oturumSetSoruOlcmeKlasiks;
		this.oturumSetSoruOlcmeDogruyanlises = oturumSetSoruOlcmeDogruyanlises;
	}

	public SetSoruId getId() {
		return this.id;
	}

	public void setId(SetSoruId id) {
		this.id = id;
	}

	public Soru getSoru() {
		return this.soru;
	}

	public void setSoru(Soru soru) {
		this.soru = soru;
	}

	public Sett getSett() {
		return this.sett;
	}

	public void setSett(Sett sett) {
		this.sett = sett;
	}

	public short getSira() {
		return this.sira;
	}

	public void setSira(short sira) {
		this.sira = sira;
	}

	public Set getOturumSetSoruOlcmeCoktansecmeliTekcevaps() {
		return this.oturumSetSoruOlcmeCoktansecmeliTekcevaps;
	}

	public void setOturumSetSoruOlcmeCoktansecmeliTekcevaps(
			Set oturumSetSoruOlcmeCoktansecmeliTekcevaps) {
		this.oturumSetSoruOlcmeCoktansecmeliTekcevaps = oturumSetSoruOlcmeCoktansecmeliTekcevaps;
	}

	public Set getOturumSetSoruOlcmeKlasiks() {
		return this.oturumSetSoruOlcmeKlasiks;
	}

	public void setOturumSetSoruOlcmeKlasiks(Set oturumSetSoruOlcmeKlasiks) {
		this.oturumSetSoruOlcmeKlasiks = oturumSetSoruOlcmeKlasiks;
	}

	public Set getOturumSetSoruOlcmeDogruyanlises() {
		return this.oturumSetSoruOlcmeDogruyanlises;
	}

	public void setOturumSetSoruOlcmeDogruyanlises(
			Set oturumSetSoruOlcmeDogruyanlises) {
		this.oturumSetSoruOlcmeDogruyanlises = oturumSetSoruOlcmeDogruyanlises;
	}

}
