package com.Argeloji.Domain;

// default package
// Generated Mar 18, 2013 10:44:04 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Sett generated by hbm2java
 */
public class Sett implements java.io.Serializable {

	private long kod;
	private Seviye seviye;
	private Settip settip;
	private long kullaniciKod;
	private Date olusturmatarih;
	private int sure;
	private short durum;
	private Set setSorus = new HashSet(0);

	public Sett() {
	}

	public Sett(long kod, Seviye seviye, Settip settip, long kullaniciKod,
			Date olusturmatarih, int sure, short durum) {
		this.kod = kod;
		this.seviye = seviye;
		this.settip = settip;
		this.kullaniciKod = kullaniciKod;
		this.olusturmatarih = olusturmatarih;
		this.sure = sure;
		this.durum = durum;
	}

	public Sett(long kod, Seviye seviye, Settip settip, long kullaniciKod,
			Date olusturmatarih, int sure, short durum, Set setSorus) {
		this.kod = kod;
		this.seviye = seviye;
		this.settip = settip;
		this.kullaniciKod = kullaniciKod;
		this.olusturmatarih = olusturmatarih;
		this.sure = sure;
		this.durum = durum;
		this.setSorus = setSorus;
	}

	public long getKod() {
		return this.kod;
	}

	public void setKod(long kod) {
		this.kod = kod;
	}

	public Seviye getSeviye() {
		return this.seviye;
	}

	public void setSeviye(Seviye seviye) {
		this.seviye = seviye;
	}

	public Settip getSettip() {
		return this.settip;
	}

	public void setSettip(Settip settip) {
		this.settip = settip;
	}

	public long getKullaniciKod() {
		return this.kullaniciKod;
	}

	public void setKullaniciKod(long kullaniciKod) {
		this.kullaniciKod = kullaniciKod;
	}

	public Date getOlusturmatarih() {
		return this.olusturmatarih;
	}

	public void setOlusturmatarih(Date olusturmatarih) {
		this.olusturmatarih = olusturmatarih;
	}

	public int getSure() {
		return this.sure;
	}

	public void setSure(int sure) {
		this.sure = sure;
	}

	public short getDurum() {
		return this.durum;
	}

	public void setDurum(short durum) {
		this.durum = durum;
	}

	public Set getSetSorus() {
		return this.setSorus;
	}

	public void setSetSorus(Set setSorus) {
		this.setSorus = setSorus;
	}

}
