package com.Argeloji.Domain;

// default package
// Generated Mar 18, 2013 10:44:04 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Settip generated by hbm2java
 */
public class Settip implements java.io.Serializable {

	private short kod;
	private String ad;
	private Set setts = new HashSet(0);

	public Settip() {
	}

	public Settip(short kod, String ad) {
		this.kod = kod;
		this.ad = ad;
	}

	public Settip(short kod, String ad, Set setts) {
		this.kod = kod;
		this.ad = ad;
		this.setts = setts;
	}

	public short getKod() {
		return this.kod;
	}

	public void setKod(short kod) {
		this.kod = kod;
	}

	public String getAd() {
		return this.ad;
	}

	public void setAd(String ad) {
		this.ad = ad;
	}

	public Set getSetts() {
		return this.setts;
	}

	public void setSetts(Set setts) {
		this.setts = setts;
	}

}
