package com.Argeloji.Domain;

// default package
// Generated Mar 19, 2013 1:29:16 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Soru generated by hbm2java
 */
public class Soru implements java.io.Serializable {

	private long kod;
	private Gorsel gorsel;
	private Kazanim kazanim;
	private Etkinlik etkinlik;
	private String sorumetin;
	private short sorumetingorselkonum;
	private short tip;
	private short seviye;
	private String cozum;
	private Set setSorus = new HashSet(0);
	private Set dogruyanlises = new HashSet(0);
	private Set coktansecmeli3Tekcevaps = new HashSet(0);
	private Set klasiks = new HashSet(0);

	public Soru() {
	}

	public Soru(long kod, Gorsel gorsel, Kazanim kazanim, Etkinlik etkinlik,
			String sorumetin, short sorumetingorselkonum, short tip,
			short seviye, String cozum) {
		this.kod = kod;
		this.gorsel = gorsel;
		this.kazanim = kazanim;
		this.etkinlik = etkinlik;
		this.sorumetin = sorumetin;
		this.sorumetingorselkonum = sorumetingorselkonum;
		this.tip = tip;
		this.seviye = seviye;
		this.cozum = cozum;
	}

	public Soru(long kod, Gorsel gorsel, Kazanim kazanim, Etkinlik etkinlik,
			String sorumetin, short sorumetingorselkonum, short tip,
			short seviye, String cozum, Set setSorus, Set dogruyanlises,
			Set coktansecmeli3Tekcevaps, Set klasiks) {
		this.kod = kod;
		this.gorsel = gorsel;
		this.kazanim = kazanim;
		this.etkinlik = etkinlik;
		this.sorumetin = sorumetin;
		this.sorumetingorselkonum = sorumetingorselkonum;
		this.tip = tip;
		this.seviye = seviye;
		this.cozum = cozum;
		this.setSorus = setSorus;
		this.dogruyanlises = dogruyanlises;
		this.coktansecmeli3Tekcevaps = coktansecmeli3Tekcevaps;
		this.klasiks = klasiks;
	}

	public long getKod() {
		return this.kod;
	}

	public void setKod(long kod) {
		this.kod = kod;
	}

	public Gorsel getGorsel() {
		return this.gorsel;
	}

	public void setGorsel(Gorsel gorsel) {
		this.gorsel = gorsel;
	}

	public Kazanim getKazanim() {
		return this.kazanim;
	}

	public void setKazanim(Kazanim kazanim) {
		this.kazanim = kazanim;
	}

	public Etkinlik getEtkinlik() {
		return this.etkinlik;
	}

	public void setEtkinlik(Etkinlik etkinlik) {
		this.etkinlik = etkinlik;
	}

	public String getSorumetin() {
		return this.sorumetin;
	}

	public void setSorumetin(String sorumetin) {
		this.sorumetin = sorumetin;
	}

	public short getSorumetingorselkonum() {
		return this.sorumetingorselkonum;
	}

	public void setSorumetingorselkonum(short sorumetingorselkonum) {
		this.sorumetingorselkonum = sorumetingorselkonum;
	}

	public short getTip() {
		return this.tip;
	}

	public void setTip(short tip) {
		this.tip = tip;
	}

	public short getSeviye() {
		return this.seviye;
	}

	public void setSeviye(short seviye) {
		this.seviye = seviye;
	}

	public String getCozum() {
		return this.cozum;
	}

	public void setCozum(String cozum) {
		this.cozum = cozum;
	}

	public Set getSetSorus() {
		return this.setSorus;
	}

	public void setSetSorus(Set setSorus) {
		this.setSorus = setSorus;
	}

	public Set getDogruyanlises() {
		return this.dogruyanlises;
	}

	public void setDogruyanlises(Set dogruyanlises) {
		this.dogruyanlises = dogruyanlises;
	}

	public Set getCoktansecmeli3Tekcevaps() {
		return this.coktansecmeli3Tekcevaps;
	}

	public void setCoktansecmeli3Tekcevaps(Set coktansecmeli3Tekcevaps) {
		this.coktansecmeli3Tekcevaps = coktansecmeli3Tekcevaps;
	}

	public Set getKlasiks() {
		return this.klasiks;
	}

	public void setKlasiks(Set klasiks) {
		this.klasiks = klasiks;
	}

}
