package com.Argeloji.Domain;

// default package
// Generated Mar 18, 2013 10:44:04 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Sube generated by hbm2java
 */
public class Sube implements java.io.Serializable {

	private int kod;
	private Sinif sinif;
	private String ad;
	private Set okulsubes = new HashSet(0);

	public Sube() {
	}

	public Sube(int kod, Sinif sinif, String ad) {
		this.kod = kod;
		this.sinif = sinif;
		this.ad = ad;
	}

	public Sube(int kod, Sinif sinif, String ad, Set okulsubes) {
		this.kod = kod;
		this.sinif = sinif;
		this.ad = ad;
		this.okulsubes = okulsubes;
	}

	public int getKod() {
		return this.kod;
	}

	public void setKod(int kod) {
		this.kod = kod;
	}

	public Sinif getSinif() {
		return this.sinif;
	}

	public void setSinif(Sinif sinif) {
		this.sinif = sinif;
	}

	public String getAd() {
		return this.ad;
	}

	public void setAd(String ad) {
		this.ad = ad;
	}

	public Set getOkulsubes() {
		return this.okulsubes;
	}

	public void setOkulsubes(Set okulsubes) {
		this.okulsubes = okulsubes;
	}

}
