package com.Argeloji.Domain;

// default package
// Generated Mar 18, 2013 10:44:04 AM by Hibernate Tools 3.4.0.CR1

/**
 * UsersGroups generated by hbm2java
 */
public class UsersGroups implements java.io.Serializable {

	private UsersGroupsId id;
	private Group group;
	private User user;

	public UsersGroups() {
	}

	public UsersGroups(UsersGroupsId id, Group group, User user) {
		this.id = id;
		this.group = group;
		this.user = user;
	}

	public UsersGroupsId getId() {
		return this.id;
	}

	public void setId(UsersGroupsId id) {
		this.id = id;
	}

	public Group getGroup() {
		return this.group;
	}

	public void setGroup(Group group) {
		this.group = group;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

}
