package com.Argeloji.Domain;

// default package
// Generated Mar 18, 2013 10:44:04 AM by Hibernate Tools 3.4.0.CR1

/**
 * UsersGroupsId generated by hbm2java
 */
public class UsersGroupsId implements java.io.Serializable {

	private long userid;
	private long groupid;

	public UsersGroupsId() {
	}

	public UsersGroupsId(long userid, long groupid) {
		this.userid = userid;
		this.groupid = groupid;
	}

	public long getUserid() {
		return this.userid;
	}

	public void setUserid(long userid) {
		this.userid = userid;
	}

	public long getGroupid() {
		return this.groupid;
	}

	public void setGroupid(long groupid) {
		this.groupid = groupid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UsersGroupsId))
			return false;
		UsersGroupsId castOther = (UsersGroupsId) other;

		return (this.getUserid() == castOther.getUserid())
				&& (this.getGroupid() == castOther.getGroupid());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getUserid();
		result = 37 * result + (int) this.getGroupid();
		return result;
	}

}
