package com.Argeloji.Domain;

// default package
// Generated Mar 18, 2013 10:44:04 AM by Hibernate Tools 3.4.0.CR1

/**
 * Useridmapper generated by hbm2java
 */
public class Useridmapper implements java.io.Serializable {

	private long useridmapperid;
	private Kullanici kullanici;
	private User user;
	private String type;
	private String description;

	public Useridmapper() {
	}

	public Useridmapper(long useridmapperid, Kullanici kullanici, User user) {
		this.useridmapperid = useridmapperid;
		this.kullanici = kullanici;
		this.user = user;
	}

	public Useridmapper(long useridmapperid, Kullanici kullanici, User user,
			String type, String description) {
		this.useridmapperid = useridmapperid;
		this.kullanici = kullanici;
		this.user = user;
		this.type = type;
		this.description = description;
	}

	public long getUseridmapperid() {
		return this.useridmapperid;
	}

	public void setUseridmapperid(long useridmapperid) {
		this.useridmapperid = useridmapperid;
	}

	public Kullanici getKullanici() {
		return this.kullanici;
	}

	public void setKullanici(Kullanici kullanici) {
		this.kullanici = kullanici;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
