package com.Argeloji.Domain;

// default package
// Generated Mar 18, 2013 10:44:04 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private long userid;
	private String uuid;
	private Long companyid;
	private Date createdate;
	private Date modifieddate;
	private Boolean defaultuser;
	private Long contactid;
	private String password;
	private Boolean passwordencrypted;
	private Boolean passwordreset;
	private Date passwordmodifieddate;
	private String digest;
	private String reminderqueryquestion;
	private String reminderqueryanswer;
	private Integer gracelogincount;
	private String screenname;
	private String emailaddress;
	private Long facebookid;
	private String openid;
	private Long portraitid;
	private String languageid;
	private String timezoneid;
	private String greeting;
	private String comments;
	private String firstname;
	private String middlename;
	private String lastname;
	private String jobtitle;
	private Date logindate;
	private String loginip;
	private Date lastlogindate;
	private String lastloginip;
	private Date lastfailedlogindate;
	private Integer failedloginattempts;
	private Boolean lockout;
	private Date lockoutdate;
	private Boolean agreedtotermsofuse;
	private Boolean emailaddressverified;
	private Integer status;
	private Set useridmappers = new HashSet(0);
	private Set usersGroupses = new HashSet(0);

	public User() {
	}

	public User(long userid) {
		this.userid = userid;
	}

	public User(long userid, String uuid, Long companyid, Date createdate,
			Date modifieddate, Boolean defaultuser, Long contactid,
			String password, Boolean passwordencrypted, Boolean passwordreset,
			Date passwordmodifieddate, String digest,
			String reminderqueryquestion, String reminderqueryanswer,
			Integer gracelogincount, String screenname, String emailaddress,
			Long facebookid, String openid, Long portraitid, String languageid,
			String timezoneid, String greeting, String comments,
			String firstname, String middlename, String lastname,
			String jobtitle, Date logindate, String loginip,
			Date lastlogindate, String lastloginip, Date lastfailedlogindate,
			Integer failedloginattempts, Boolean lockout, Date lockoutdate,
			Boolean agreedtotermsofuse, Boolean emailaddressverified,
			Integer status, Set useridmappers, Set usersGroupses) {
		this.userid = userid;
		this.uuid = uuid;
		this.companyid = companyid;
		this.createdate = createdate;
		this.modifieddate = modifieddate;
		this.defaultuser = defaultuser;
		this.contactid = contactid;
		this.password = password;
		this.passwordencrypted = passwordencrypted;
		this.passwordreset = passwordreset;
		this.passwordmodifieddate = passwordmodifieddate;
		this.digest = digest;
		this.reminderqueryquestion = reminderqueryquestion;
		this.reminderqueryanswer = reminderqueryanswer;
		this.gracelogincount = gracelogincount;
		this.screenname = screenname;
		this.emailaddress = emailaddress;
		this.facebookid = facebookid;
		this.openid = openid;
		this.portraitid = portraitid;
		this.languageid = languageid;
		this.timezoneid = timezoneid;
		this.greeting = greeting;
		this.comments = comments;
		this.firstname = firstname;
		this.middlename = middlename;
		this.lastname = lastname;
		this.jobtitle = jobtitle;
		this.logindate = logindate;
		this.loginip = loginip;
		this.lastlogindate = lastlogindate;
		this.lastloginip = lastloginip;
		this.lastfailedlogindate = lastfailedlogindate;
		this.failedloginattempts = failedloginattempts;
		this.lockout = lockout;
		this.lockoutdate = lockoutdate;
		this.agreedtotermsofuse = agreedtotermsofuse;
		this.emailaddressverified = emailaddressverified;
		this.status = status;
		this.useridmappers = useridmappers;
		this.usersGroupses = usersGroupses;
	}

	public long getUserid() {
		return this.userid;
	}

	public void setUserid(long userid) {
		this.userid = userid;
	}

	public String getUuid() {
		return this.uuid;
	}

	public void setUuid(String uuid) {
		this.uuid = uuid;
	}

	public Long getCompanyid() {
		return this.companyid;
	}

	public void setCompanyid(Long companyid) {
		this.companyid = companyid;
	}

	public Date getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

	public Date getModifieddate() {
		return this.modifieddate;
	}

	public void setModifieddate(Date modifieddate) {
		this.modifieddate = modifieddate;
	}

	public Boolean getDefaultuser() {
		return this.defaultuser;
	}

	public void setDefaultuser(Boolean defaultuser) {
		this.defaultuser = defaultuser;
	}

	public Long getContactid() {
		return this.contactid;
	}

	public void setContactid(Long contactid) {
		this.contactid = contactid;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Boolean getPasswordencrypted() {
		return this.passwordencrypted;
	}

	public void setPasswordencrypted(Boolean passwordencrypted) {
		this.passwordencrypted = passwordencrypted;
	}

	public Boolean getPasswordreset() {
		return this.passwordreset;
	}

	public void setPasswordreset(Boolean passwordreset) {
		this.passwordreset = passwordreset;
	}

	public Date getPasswordmodifieddate() {
		return this.passwordmodifieddate;
	}

	public void setPasswordmodifieddate(Date passwordmodifieddate) {
		this.passwordmodifieddate = passwordmodifieddate;
	}

	public String getDigest() {
		return this.digest;
	}

	public void setDigest(String digest) {
		this.digest = digest;
	}

	public String getReminderqueryquestion() {
		return this.reminderqueryquestion;
	}

	public void setReminderqueryquestion(String reminderqueryquestion) {
		this.reminderqueryquestion = reminderqueryquestion;
	}

	public String getReminderqueryanswer() {
		return this.reminderqueryanswer;
	}

	public void setReminderqueryanswer(String reminderqueryanswer) {
		this.reminderqueryanswer = reminderqueryanswer;
	}

	public Integer getGracelogincount() {
		return this.gracelogincount;
	}

	public void setGracelogincount(Integer gracelogincount) {
		this.gracelogincount = gracelogincount;
	}

	public String getScreenname() {
		return this.screenname;
	}

	public void setScreenname(String screenname) {
		this.screenname = screenname;
	}

	public String getEmailaddress() {
		return this.emailaddress;
	}

	public void setEmailaddress(String emailaddress) {
		this.emailaddress = emailaddress;
	}

	public Long getFacebookid() {
		return this.facebookid;
	}

	public void setFacebookid(Long facebookid) {
		this.facebookid = facebookid;
	}

	public String getOpenid() {
		return this.openid;
	}

	public void setOpenid(String openid) {
		this.openid = openid;
	}

	public Long getPortraitid() {
		return this.portraitid;
	}

	public void setPortraitid(Long portraitid) {
		this.portraitid = portraitid;
	}

	public String getLanguageid() {
		return this.languageid;
	}

	public void setLanguageid(String languageid) {
		this.languageid = languageid;
	}

	public String getTimezoneid() {
		return this.timezoneid;
	}

	public void setTimezoneid(String timezoneid) {
		this.timezoneid = timezoneid;
	}

	public String getGreeting() {
		return this.greeting;
	}

	public void setGreeting(String greeting) {
		this.greeting = greeting;
	}

	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	public String getMiddlename() {
		return this.middlename;
	}

	public void setMiddlename(String middlename) {
		this.middlename = middlename;
	}

	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	public String getJobtitle() {
		return this.jobtitle;
	}

	public void setJobtitle(String jobtitle) {
		this.jobtitle = jobtitle;
	}

	public Date getLogindate() {
		return this.logindate;
	}

	public void setLogindate(Date logindate) {
		this.logindate = logindate;
	}

	public String getLoginip() {
		return this.loginip;
	}

	public void setLoginip(String loginip) {
		this.loginip = loginip;
	}

	public Date getLastlogindate() {
		return this.lastlogindate;
	}

	public void setLastlogindate(Date lastlogindate) {
		this.lastlogindate = lastlogindate;
	}

	public String getLastloginip() {
		return this.lastloginip;
	}

	public void setLastloginip(String lastloginip) {
		this.lastloginip = lastloginip;
	}

	public Date getLastfailedlogindate() {
		return this.lastfailedlogindate;
	}

	public void setLastfailedlogindate(Date lastfailedlogindate) {
		this.lastfailedlogindate = lastfailedlogindate;
	}

	public Integer getFailedloginattempts() {
		return this.failedloginattempts;
	}

	public void setFailedloginattempts(Integer failedloginattempts) {
		this.failedloginattempts = failedloginattempts;
	}

	public Boolean getLockout() {
		return this.lockout;
	}

	public void setLockout(Boolean lockout) {
		this.lockout = lockout;
	}

	public Date getLockoutdate() {
		return this.lockoutdate;
	}

	public void setLockoutdate(Date lockoutdate) {
		this.lockoutdate = lockoutdate;
	}

	public Boolean getAgreedtotermsofuse() {
		return this.agreedtotermsofuse;
	}

	public void setAgreedtotermsofuse(Boolean agreedtotermsofuse) {
		this.agreedtotermsofuse = agreedtotermsofuse;
	}

	public Boolean getEmailaddressverified() {
		return this.emailaddressverified;
	}

	public void setEmailaddressverified(Boolean emailaddressverified) {
		this.emailaddressverified = emailaddressverified;
	}

	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public Set getUseridmappers() {
		return this.useridmappers;
	}

	public void setUseridmappers(Set useridmappers) {
		this.useridmappers = useridmappers;
	}

	public Set getUsersGroupses() {
		return this.usersGroupses;
	}

	public void setUsersGroupses(Set usersGroupses) {
		this.usersGroupses = usersGroupses;
	}

}
