package com.Argeloji.Domain;

// default package
// Generated Mar 18, 2013 10:44:04 AM by Hibernate Tools 3.4.0.CR1

/**
 * UygulamaMetaveriId generated by hbm2java
 */
public class UygulamaMetaveriId implements java.io.Serializable {

	private int uygulamaKod;
	private int metavarlikTip;
	private int metavarlikKod;

	public UygulamaMetaveriId() {
	}

	public UygulamaMetaveriId(int uygulamaKod, int metavarlikTip,
			int metavarlikKod) {
		this.uygulamaKod = uygulamaKod;
		this.metavarlikTip = metavarlikTip;
		this.metavarlikKod = metavarlikKod;
	}

	public int getUygulamaKod() {
		return this.uygulamaKod;
	}

	public void setUygulamaKod(int uygulamaKod) {
		this.uygulamaKod = uygulamaKod;
	}

	public int getMetavarlikTip() {
		return this.metavarlikTip;
	}

	public void setMetavarlikTip(int metavarlikTip) {
		this.metavarlikTip = metavarlikTip;
	}

	public int getMetavarlikKod() {
		return this.metavarlikKod;
	}

	public void setMetavarlikKod(int metavarlikKod) {
		this.metavarlikKod = metavarlikKod;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UygulamaMetaveriId))
			return false;
		UygulamaMetaveriId castOther = (UygulamaMetaveriId) other;

		return (this.getUygulamaKod() == castOther.getUygulamaKod())
				&& (this.getMetavarlikTip() == castOther.getMetavarlikTip())
				&& (this.getMetavarlikKod() == castOther.getMetavarlikKod());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getUygulamaKod();
		result = 37 * result + this.getMetavarlikTip();
		result = 37 * result + this.getMetavarlikKod();
		return result;
	}

}
