package com.Argeloji.Domain;

// default package
// Generated Mar 18, 2013 10:44:04 AM by Hibernate Tools 3.4.0.CR1

/**
 * UygulamaCihazId generated by hbm2java
 */
public class UygulamaCihazId implements java.io.Serializable {

	private int uygulamaKod;
	private long cihazKod;

	public UygulamaCihazId() {
	}

	public UygulamaCihazId(int uygulamaKod, long cihazKod) {
		this.uygulamaKod = uygulamaKod;
		this.cihazKod = cihazKod;
	}

	public int getUygulamaKod() {
		return this.uygulamaKod;
	}

	public void setUygulamaKod(int uygulamaKod) {
		this.uygulamaKod = uygulamaKod;
	}

	public long getCihazKod() {
		return this.cihazKod;
	}

	public void setCihazKod(long cihazKod) {
		this.cihazKod = cihazKod;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UygulamaCihazId))
			return false;
		UygulamaCihazId castOther = (UygulamaCihazId) other;

		return (this.getUygulamaKod() == castOther.getUygulamaKod())
				&& (this.getCihazKod() == castOther.getCihazKod());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getUygulamaKod();
		result = 37 * result + (int) this.getCihazKod();
		return result;
	}

}
