package com.Argeloji.Domain;

import com.Argeloji.Domain.Kullanici;
import com.Argeloji.Domain.UygulamaCihaz;
// default package
// Generated 14.Mar.2013 16:04:45 by Hibernate Tools 4.0.0

/**
 * UygulamaKullanici generated by hbm2java
 */
public class UygulamaKullanici implements java.io.Serializable {
	private long kullaniciKod;
	private UygulamaCihaz uygulamaCihaz;
	private Kullanici kullanici;

	public UygulamaKullanici() {
	}

	public UygulamaKullanici(UygulamaCihaz uygulamaCihaz, Kullanici kullanici) {
		this.uygulamaCihaz = uygulamaCihaz;
		this.kullanici = kullanici;
	}

	public long getKullaniciKod() {
		return this.kullaniciKod;
	}

	public void setKullaniciKod(long kullaniciKod) {
		this.kullaniciKod = kullaniciKod;
	}

	public UygulamaCihaz getUygulamaCihaz() {
		return this.uygulamaCihaz;
	}

	public void setUygulamaCihaz(UygulamaCihaz uygulamaCihaz) {
		this.uygulamaCihaz = uygulamaCihaz;
	}

	public Kullanici getKullanici() {
		return this.kullanici;
	}

	public void setKullanici(Kullanici kullanici) {
		this.kullanici = kullanici;
	}


}
