package com.Argeloji.Domain;

// default package
// Generated Mar 18, 2013 10:44:04 AM by Hibernate Tools 3.4.0.CR1

/**
 * UygulamaKullanici generated by hbm2java
 */
public class UygulamaKullanici implements java.io.Serializable {

	private long kullaniciKod;
	private UygulamaCihaz uygulamaCihaz;
	private Kullanici kullanici;

	public UygulamaKullanici() {
	}

	public UygulamaKullanici(long kullaniciKod, UygulamaCihaz uygulamaCihaz,
			Kullanici kullanici) {
		this.kullaniciKod = kullaniciKod;
		this.uygulamaCihaz = uygulamaCihaz;
		this.kullanici = kullanici;
	}

	public long getKullaniciKod() {
		return this.kullaniciKod;
	}

	public void setKullaniciKod(long kullaniciKod) {
		this.kullaniciKod = kullaniciKod;
	}

	public UygulamaCihaz getUygulamaCihaz() {
		return this.uygulamaCihaz;
	}

	public void setUygulamaCihaz(UygulamaCihaz uygulamaCihaz) {
		this.uygulamaCihaz = uygulamaCihaz;
	}

	public Kullanici getKullanici() {
		return this.kullanici;
	}

	public void setKullanici(Kullanici kullanici) {
		this.kullanici = kullanici;
	}

}
