package com.Argeloji.Domain;

// default package
// Generated Mar 18, 2013 10:44:04 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Veliokul generated by hbm2java
 */
public class Veliokul implements java.io.Serializable {

	private VeliokulId id;
	private Okul okul;
	private Veli veli;
	private Date cikistarih;

	public Veliokul() {
	}

	public Veliokul(VeliokulId id, Okul okul, Veli veli, Date cikistarih) {
		this.id = id;
		this.okul = okul;
		this.veli = veli;
		this.cikistarih = cikistarih;
	}

	public VeliokulId getId() {
		return this.id;
	}

	public void setId(VeliokulId id) {
		this.id = id;
	}

	public Okul getOkul() {
		return this.okul;
	}

	public void setOkul(Okul okul) {
		this.okul = okul;
	}

	public Veli getVeli() {
		return this.veli;
	}

	public void setVeli(Veli veli) {
		this.veli = veli;
	}

	public Date getCikistarih() {
		return this.cikistarih;
	}

	public void setCikistarih(Date cikistarih) {
		this.cikistarih = cikistarih;
	}

}
