package com.Argeloji.Domain;

// default package
// Generated Mar 18, 2013 10:44:04 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Veliogrenci generated by hbm2java
 */
public class Veliogrenci implements java.io.Serializable {

	private VeliogrenciId id;
	private Ogrenci ogrenci;
	private Veli veli;
	private Date cikiszaman;

	public Veliogrenci() {
	}

	public Veliogrenci(VeliogrenciId id, Ogrenci ogrenci, Veli veli,
			Date cikiszaman) {
		this.id = id;
		this.ogrenci = ogrenci;
		this.veli = veli;
		this.cikiszaman = cikiszaman;
	}

	public VeliogrenciId getId() {
		return this.id;
	}

	public void setId(VeliogrenciId id) {
		this.id = id;
	}

	public Ogrenci getOgrenci() {
		return this.ogrenci;
	}

	public void setOgrenci(Ogrenci ogrenci) {
		this.ogrenci = ogrenci;
	}

	public Veli getVeli() {
		return this.veli;
	}

	public void setVeli(Veli veli) {
		this.veli = veli;
	}

	public Date getCikiszaman() {
		return this.cikiszaman;
	}

	public void setCikiszaman(Date cikiszaman) {
		this.cikiszaman = cikiszaman;
	}

}
