package com.Argeloji.Domain;

// default package
// Generated Mar 18, 2013 10:44:04 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * VeliogrenciId generated by hbm2java
 */
public class VeliogrenciId implements java.io.Serializable {

	private long kullaniciVeliKod;
	private long kullaniciOgrenciKod;
	private Date giriszaman;

	public VeliogrenciId() {
	}

	public VeliogrenciId(long kullaniciVeliKod, long kullaniciOgrenciKod,
			Date giriszaman) {
		this.kullaniciVeliKod = kullaniciVeliKod;
		this.kullaniciOgrenciKod = kullaniciOgrenciKod;
		this.giriszaman = giriszaman;
	}

	public long getKullaniciVeliKod() {
		return this.kullaniciVeliKod;
	}

	public void setKullaniciVeliKod(long kullaniciVeliKod) {
		this.kullaniciVeliKod = kullaniciVeliKod;
	}

	public long getKullaniciOgrenciKod() {
		return this.kullaniciOgrenciKod;
	}

	public void setKullaniciOgrenciKod(long kullaniciOgrenciKod) {
		this.kullaniciOgrenciKod = kullaniciOgrenciKod;
	}

	public Date getGiriszaman() {
		return this.giriszaman;
	}

	public void setGiriszaman(Date giriszaman) {
		this.giriszaman = giriszaman;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VeliogrenciId))
			return false;
		VeliogrenciId castOther = (VeliogrenciId) other;

		return (this.getKullaniciVeliKod() == castOther.getKullaniciVeliKod())
				&& (this.getKullaniciOgrenciKod() == castOther
						.getKullaniciOgrenciKod())
				&& ((this.getGiriszaman() == castOther.getGiriszaman()) || (this
						.getGiriszaman() != null
						&& castOther.getGiriszaman() != null && this
						.getGiriszaman().equals(castOther.getGiriszaman())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getKullaniciVeliKod();
		result = 37 * result + (int) this.getKullaniciOgrenciKod();
		result = 37
				* result
				+ (getGiriszaman() == null ? 0 : this.getGiriszaman()
						.hashCode());
		return result;
	}

}
