package com.Argeloji.Domain;

// default package
// Generated Mar 18, 2013 10:44:04 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Veli generated by hbm2java
 */
public class Veli implements java.io.Serializable {

	private long kullaniciKod;
	private Kullanici kullanici;
	private int istelefon;
	private String meslek;
	private Set veliogrencis = new HashSet(0);
	private Set oabvelis = new HashSet(0);
	private Set veliokuls = new HashSet(0);

	public Veli() {
	}

	public Veli(long kullaniciKod, Kullanici kullanici, int istelefon,
			String meslek) {
		this.kullaniciKod = kullaniciKod;
		this.kullanici = kullanici;
		this.istelefon = istelefon;
		this.meslek = meslek;
	}

	public Veli(long kullaniciKod, Kullanici kullanici, int istelefon,
			String meslek, Set veliogrencis, Set oabvelis, Set veliokuls) {
		this.kullaniciKod = kullaniciKod;
		this.kullanici = kullanici;
		this.istelefon = istelefon;
		this.meslek = meslek;
		this.veliogrencis = veliogrencis;
		this.oabvelis = oabvelis;
		this.veliokuls = veliokuls;
	}

	public long getKullaniciKod() {
		return this.kullaniciKod;
	}

	public void setKullaniciKod(long kullaniciKod) {
		this.kullaniciKod = kullaniciKod;
	}

	public Kullanici getKullanici() {
		return this.kullanici;
	}

	public void setKullanici(Kullanici kullanici) {
		this.kullanici = kullanici;
	}

	public int getIstelefon() {
		return this.istelefon;
	}

	public void setIstelefon(int istelefon) {
		this.istelefon = istelefon;
	}

	public String getMeslek() {
		return this.meslek;
	}

	public void setMeslek(String meslek) {
		this.meslek = meslek;
	}

	public Set getVeliogrencis() {
		return this.veliogrencis;
	}

	public void setVeliogrencis(Set veliogrencis) {
		this.veliogrencis = veliogrencis;
	}

	public Set getOabvelis() {
		return this.oabvelis;
	}

	public void setOabvelis(Set oabvelis) {
		this.oabvelis = oabvelis;
	}

	public Set getVeliokuls() {
		return this.veliokuls;
	}

	public void setVeliokuls(Set veliokuls) {
		this.veliokuls = veliokuls;
	}

}
