package com.Argeloji.Domain;

// default package
// Generated Mar 18, 2013 10:44:04 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Yardimcioda generated by hbm2java
 */
public class Yardimcioda implements java.io.Serializable {

	private YardimciodaId id;
	private Altyapi altyapi;
	private String tip;
	private int kapasite;
	private Date giristarih;
	private Date cikistarih;
	private String ad;

	public Yardimcioda() {
	}

	public Yardimcioda(YardimciodaId id, Altyapi altyapi, String tip,
			int kapasite, Date giristarih, Date cikistarih, String ad) {
		this.id = id;
		this.altyapi = altyapi;
		this.tip = tip;
		this.kapasite = kapasite;
		this.giristarih = giristarih;
		this.cikistarih = cikistarih;
		this.ad = ad;
	}

	public YardimciodaId getId() {
		return this.id;
	}

	public void setId(YardimciodaId id) {
		this.id = id;
	}

	public Altyapi getAltyapi() {
		return this.altyapi;
	}

	public void setAltyapi(Altyapi altyapi) {
		this.altyapi = altyapi;
	}

	public String getTip() {
		return this.tip;
	}

	public void setTip(String tip) {
		this.tip = tip;
	}

	public int getKapasite() {
		return this.kapasite;
	}

	public void setKapasite(int kapasite) {
		this.kapasite = kapasite;
	}

	public Date getGiristarih() {
		return this.giristarih;
	}

	public void setGiristarih(Date giristarih) {
		this.giristarih = giristarih;
	}

	public Date getCikistarih() {
		return this.cikistarih;
	}

	public void setCikistarih(Date cikistarih) {
		this.cikistarih = cikistarih;
	}

	public String getAd() {
		return this.ad;
	}

	public void setAd(String ad) {
		this.ad = ad;
	}

}
