package com.Argeloji.Domain;

// default package
// Generated Mar 18, 2013 10:44:04 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Yonetimpersonel generated by hbm2java
 */
public class Yonetimpersonel implements java.io.Serializable {

	private YonetimpersonelId id;
	private Personel personel;
	private Yonetim yonetim;
	private Date cikistarih;

	public Yonetimpersonel() {
	}

	public Yonetimpersonel(YonetimpersonelId id, Personel personel,
			Yonetim yonetim, Date cikistarih) {
		this.id = id;
		this.personel = personel;
		this.yonetim = yonetim;
		this.cikistarih = cikistarih;
	}

	public YonetimpersonelId getId() {
		return this.id;
	}

	public void setId(YonetimpersonelId id) {
		this.id = id;
	}

	public Personel getPersonel() {
		return this.personel;
	}

	public void setPersonel(Personel personel) {
		this.personel = personel;
	}

	public Yonetim getYonetim() {
		return this.yonetim;
	}

	public void setYonetim(Yonetim yonetim) {
		this.yonetim = yonetim;
	}

	public Date getCikistarih() {
		return this.cikistarih;
	}

	public void setCikistarih(Date cikistarih) {
		this.cikistarih = cikistarih;
	}

}
