package com.Argeloji.Domain;

// default package
// Generated Mar 18, 2013 10:44:04 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * YonetimpersonelId generated by hbm2java
 */
public class YonetimpersonelId implements java.io.Serializable {

	private int yonetimKod;
	private long kullaniciPersonelKod;
	private Date giristarih;

	public YonetimpersonelId() {
	}

	public YonetimpersonelId(int yonetimKod, long kullaniciPersonelKod,
			Date giristarih) {
		this.yonetimKod = yonetimKod;
		this.kullaniciPersonelKod = kullaniciPersonelKod;
		this.giristarih = giristarih;
	}

	public int getYonetimKod() {
		return this.yonetimKod;
	}

	public void setYonetimKod(int yonetimKod) {
		this.yonetimKod = yonetimKod;
	}

	public long getKullaniciPersonelKod() {
		return this.kullaniciPersonelKod;
	}

	public void setKullaniciPersonelKod(long kullaniciPersonelKod) {
		this.kullaniciPersonelKod = kullaniciPersonelKod;
	}

	public Date getGiristarih() {
		return this.giristarih;
	}

	public void setGiristarih(Date giristarih) {
		this.giristarih = giristarih;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof YonetimpersonelId))
			return false;
		YonetimpersonelId castOther = (YonetimpersonelId) other;

		return (this.getYonetimKod() == castOther.getYonetimKod())
				&& (this.getKullaniciPersonelKod() == castOther
						.getKullaniciPersonelKod())
				&& ((this.getGiristarih() == castOther.getGiristarih()) || (this
						.getGiristarih() != null
						&& castOther.getGiristarih() != null && this
						.getGiristarih().equals(castOther.getGiristarih())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getYonetimKod();
		result = 37 * result + (int) this.getKullaniciPersonelKod();
		result = 37
				* result
				+ (getGiristarih() == null ? 0 : this.getGiristarih()
						.hashCode());
		return result;
	}

}
