package com.Argeloji.Domain;

// default package
// Generated Mar 18, 2013 10:44:04 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * ZumreogretmenId generated by hbm2java
 */
public class ZumreogretmenId implements java.io.Serializable {

	private long kullaniciPersonelKod;
	private Date giristarih;
	private int zumreKod;

	public ZumreogretmenId() {
	}

	public ZumreogretmenId(long kullaniciPersonelKod, Date giristarih,
			int zumreKod) {
		this.kullaniciPersonelKod = kullaniciPersonelKod;
		this.giristarih = giristarih;
		this.zumreKod = zumreKod;
	}

	public long getKullaniciPersonelKod() {
		return this.kullaniciPersonelKod;
	}

	public void setKullaniciPersonelKod(long kullaniciPersonelKod) {
		this.kullaniciPersonelKod = kullaniciPersonelKod;
	}

	public Date getGiristarih() {
		return this.giristarih;
	}

	public void setGiristarih(Date giristarih) {
		this.giristarih = giristarih;
	}

	public int getZumreKod() {
		return this.zumreKod;
	}

	public void setZumreKod(int zumreKod) {
		this.zumreKod = zumreKod;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ZumreogretmenId))
			return false;
		ZumreogretmenId castOther = (ZumreogretmenId) other;

		return (this.getKullaniciPersonelKod() == castOther
				.getKullaniciPersonelKod())
				&& ((this.getGiristarih() == castOther.getGiristarih()) || (this
						.getGiristarih() != null
						&& castOther.getGiristarih() != null && this
						.getGiristarih().equals(castOther.getGiristarih())))
				&& (this.getZumreKod() == castOther.getZumreKod());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getKullaniciPersonelKod();
		result = 37
				* result
				+ (getGiristarih() == null ? 0 : this.getGiristarih()
						.hashCode());
		result = 37 * result + this.getZumreKod();
		return result;
	}

}
