package com.Argeloji.Domain;

// default package
// Generated Mar 18, 2013 10:44:04 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Zumre generated by hbm2java
 */
public class Zumre implements java.io.Serializable {

	private int kod;
	private Kullanicigrup kullanicigrup;
	private String alanadi;
	private Date giristarih;
	private Date cikistarih;
	private Set okulzumres = new HashSet(0);
	private Set zumreogretmens = new HashSet(0);

	public Zumre() {
	}

	public Zumre(int kod, Kullanicigrup kullanicigrup, String alanadi,
			Date giristarih, Date cikistarih) {
		this.kod = kod;
		this.kullanicigrup = kullanicigrup;
		this.alanadi = alanadi;
		this.giristarih = giristarih;
		this.cikistarih = cikistarih;
	}

	public Zumre(int kod, Kullanicigrup kullanicigrup, String alanadi,
			Date giristarih, Date cikistarih, Set okulzumres, Set zumreogretmens) {
		this.kod = kod;
		this.kullanicigrup = kullanicigrup;
		this.alanadi = alanadi;
		this.giristarih = giristarih;
		this.cikistarih = cikistarih;
		this.okulzumres = okulzumres;
		this.zumreogretmens = zumreogretmens;
	}

	public int getKod() {
		return this.kod;
	}

	public void setKod(int kod) {
		this.kod = kod;
	}

	public Kullanicigrup getKullanicigrup() {
		return this.kullanicigrup;
	}

	public void setKullanicigrup(Kullanicigrup kullanicigrup) {
		this.kullanicigrup = kullanicigrup;
	}

	public String getAlanadi() {
		return this.alanadi;
	}

	public void setAlanadi(String alanadi) {
		this.alanadi = alanadi;
	}

	public Date getGiristarih() {
		return this.giristarih;
	}

	public void setGiristarih(Date giristarih) {
		this.giristarih = giristarih;
	}

	public Date getCikistarih() {
		return this.cikistarih;
	}

	public void setCikistarih(Date cikistarih) {
		this.cikistarih = cikistarih;
	}

	public Set getOkulzumres() {
		return this.okulzumres;
	}

	public void setOkulzumres(Set okulzumres) {
		this.okulzumres = okulzumres;
	}

	public Set getZumreogretmens() {
		return this.zumreogretmens;
	}

	public void setZumreogretmens(Set zumreogretmens) {
		this.zumreogretmens = zumreogretmens;
	}

}
